// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class ProfileCategories implements SupadartClass<ProfileCategories> {
  final String id;
  final String userId;
  final String categoryId;
  final bool? isFavorite;
  final bool? isShortcut;
  final int? progress;
  final DateTime? lastCheckinAt;
  final int? checkinCount;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final int? totalCheckins;
  final num? averageWellnessLevel;
  final Map<String, dynamic>? metadata;

  const ProfileCategories({
    required this.id,
    required this.userId,
    required this.categoryId,
    this.isFavorite,
    this.isShortcut,
    this.progress,
    this.lastCheckinAt,
    this.checkinCount,
    this.createdAt,
    this.updatedAt,
    this.totalCheckins,
    this.averageWellnessLevel,
    this.metadata,
  });

  static String get table_name => 'profile_categories';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_categoryId => 'category_id';
  static String get c_isFavorite => 'is_favorite';
  static String get c_isShortcut => 'is_shortcut';
  static String get c_progress => 'progress';
  static String get c_lastCheckinAt => 'last_checkin_at';
  static String get c_checkinCount => 'checkin_count';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_totalCheckins => 'total_checkins';
  static String get c_averageWellnessLevel => 'average_wellness_level';
  static String get c_metadata => 'metadata';

  static List<ProfileCategories> converter(List<Map<String, dynamic>> data) {
    return data.map(ProfileCategories.fromJson).toList();
  }

  static ProfileCategories converterSingle(Map<String, dynamic> data) {
    return ProfileCategories.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? categoryId,
    bool? isFavorite,
    bool? isShortcut,
    int? progress,
    DateTime? lastCheckinAt,
    int? checkinCount,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? totalCheckins,
    num? averageWellnessLevel,
    Map<String, dynamic>? metadata,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (isFavorite != null) 'is_favorite': isFavorite,
      if (isShortcut != null) 'is_shortcut': isShortcut,
      if (progress != null) 'progress': progress,
      if (lastCheckinAt != null)
        'last_checkin_at': lastCheckinAt.toUtc().toIso8601String(),
      if (checkinCount != null) 'checkin_count': checkinCount,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (totalCheckins != null) 'total_checkins': totalCheckins,
      if (averageWellnessLevel != null)
        'average_wellness_level': averageWellnessLevel.toString(),
      if (metadata != null) 'metadata': metadata,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String userId,
    required String categoryId,
    bool? isFavorite,
    bool? isShortcut,
    int? progress,
    DateTime? lastCheckinAt,
    int? checkinCount,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? totalCheckins,
    num? averageWellnessLevel,
    Map<String, dynamic>? metadata,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      isFavorite: isFavorite,
      isShortcut: isShortcut,
      progress: progress,
      lastCheckinAt: lastCheckinAt,
      checkinCount: checkinCount,
      createdAt: createdAt,
      updatedAt: updatedAt,
      totalCheckins: totalCheckins,
      averageWellnessLevel: averageWellnessLevel,
      metadata: metadata,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? categoryId,
    bool? isFavorite,
    bool? isShortcut,
    int? progress,
    DateTime? lastCheckinAt,
    int? checkinCount,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? totalCheckins,
    num? averageWellnessLevel,
    Map<String, dynamic>? metadata,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      isFavorite: isFavorite,
      isShortcut: isShortcut,
      progress: progress,
      lastCheckinAt: lastCheckinAt,
      checkinCount: checkinCount,
      createdAt: createdAt,
      updatedAt: updatedAt,
      totalCheckins: totalCheckins,
      averageWellnessLevel: averageWellnessLevel,
      metadata: metadata,
    );
  }

  factory ProfileCategories.fromJson(Map<String, dynamic> jsonn) {
    return ProfileCategories(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      categoryId:
          jsonn['category_id'] != null ? jsonn['category_id'].toString() : '',
      isFavorite:
          jsonn['is_favorite'] != null ? jsonn['is_favorite'] as bool : null,
      isShortcut:
          jsonn['is_shortcut'] != null ? jsonn['is_shortcut'] as bool : null,
      progress: jsonn['progress'] != null
          ? int.parse(jsonn['progress'].toString())
          : null,
      lastCheckinAt: jsonn['last_checkin_at'] != null
          ? DateTime.parse(jsonn['last_checkin_at'].toString())
          : null,
      checkinCount: jsonn['checkin_count'] != null
          ? int.parse(jsonn['checkin_count'].toString())
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      totalCheckins: jsonn['total_checkins'] != null
          ? int.parse(jsonn['total_checkins'].toString())
          : null,
      averageWellnessLevel: jsonn['average_wellness_level'] != null
          ? num.parse(jsonn['average_wellness_level'].toString())
          : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? categoryId,
    bool? isFavorite,
    bool? isShortcut,
    int? progress,
    DateTime? lastCheckinAt,
    int? checkinCount,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? totalCheckins,
    num? averageWellnessLevel,
    Map<String, dynamic>? metadata,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (isFavorite != null) 'is_favorite': isFavorite,
      if (isShortcut != null) 'is_shortcut': isShortcut,
      if (progress != null) 'progress': progress,
      if (lastCheckinAt != null) 'last_checkin_at': lastCheckinAt,
      if (checkinCount != null) 'checkin_count': checkinCount,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (totalCheckins != null) 'total_checkins': totalCheckins,
      if (averageWellnessLevel != null)
        'average_wellness_level': averageWellnessLevel,
      if (metadata != null) 'metadata': metadata,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      isFavorite: isFavorite,
      isShortcut: isShortcut,
      progress: progress,
      lastCheckinAt: lastCheckinAt,
      checkinCount: checkinCount,
      createdAt: createdAt,
      updatedAt: updatedAt,
      totalCheckins: totalCheckins,
      averageWellnessLevel: averageWellnessLevel,
      metadata: metadata,
    );
  }

  static const _unset = Object();
  ProfileCategories copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? categoryId = _unset,
    Object? isFavorite = _unset,
    Object? isShortcut = _unset,
    Object? progress = _unset,
    Object? lastCheckinAt = _unset,
    Object? checkinCount = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? totalCheckins = _unset,
    Object? averageWellnessLevel = _unset,
    Object? metadata = _unset,
  }) {
    return ProfileCategories(
      id: id == _unset ? this.id : id as String,
      userId: userId == _unset ? this.userId : userId as String,
      categoryId: categoryId == _unset ? this.categoryId : categoryId as String,
      isFavorite: isFavorite == _unset ? this.isFavorite : isFavorite as bool?,
      isShortcut: isShortcut == _unset ? this.isShortcut : isShortcut as bool?,
      progress: progress == _unset ? this.progress : progress as int?,
      lastCheckinAt: lastCheckinAt == _unset
          ? this.lastCheckinAt
          : lastCheckinAt as DateTime?,
      checkinCount:
          checkinCount == _unset ? this.checkinCount : checkinCount as int?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      totalCheckins:
          totalCheckins == _unset ? this.totalCheckins : totalCheckins as int?,
      averageWellnessLevel: averageWellnessLevel == _unset
          ? this.averageWellnessLevel
          : averageWellnessLevel as num?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
    );
  }
}
