// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Profiles implements SupadartClass<Profiles> {
  final String id;
  final String? name;
  final String? coachId;
  final int? yearOfBirth;
  final String? sex;
  final Map<String, dynamic>? notificationSettings;
  final Map<String, dynamic>? moodConfig;
  final bool? voiceEnabled;
  final String? languageCode;
  final String? timezone;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final Map<String, dynamic>? coach;
  final String? avatarUrl;
  final Map<String, dynamic>? metadata;
  final String? firstName;
  final String? lastName;
  final DateTime? birthDate;
  final bool? isTester;
  final int? birthYear;
  final bool? summarizationEnabled;
  final String? email;
  final String? phoneNumber;
  final String? imageUrl;
  final DateTime? lastSeenAt;
  final DateTime? lastLogin;

  const Profiles({
    required this.id,
    this.name,
    this.coachId,
    this.yearOfBirth,
    this.sex,
    this.notificationSettings,
    this.moodConfig,
    this.voiceEnabled,
    this.languageCode,
    this.timezone,
    this.createdAt,
    this.updatedAt,
    this.coach,
    this.avatarUrl,
    this.metadata,
    this.firstName,
    this.lastName,
    this.birthDate,
    this.isTester,
    this.birthYear,
    this.summarizationEnabled,
    this.email,
    this.phoneNumber,
    this.imageUrl,
    this.lastSeenAt,
    this.lastLogin,
  });

  static String get table_name => 'profiles';
  static String get c_id => 'id';
  static String get c_name => 'name';
  static String get c_coachId => 'coach_id';
  static String get c_yearOfBirth => 'year_of_birth';
  static String get c_sex => 'sex';
  static String get c_notificationSettings => 'notification_settings';
  static String get c_moodConfig => 'mood_config';
  static String get c_voiceEnabled => 'voice_enabled';
  static String get c_languageCode => 'language_code';
  static String get c_timezone => 'timezone';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_coach => 'coach';
  static String get c_avatarUrl => 'avatar_url';
  static String get c_metadata => 'metadata';
  static String get c_firstName => 'first_name';
  static String get c_lastName => 'last_name';
  static String get c_birthDate => 'birth_date';
  static String get c_isTester => 'is_tester';
  static String get c_birthYear => 'birth_year';
  static String get c_summarizationEnabled => 'summarization_enabled';
  static String get c_email => 'email';
  static String get c_phoneNumber => 'phone_number';
  static String get c_imageUrl => 'image_url';
  static String get c_lastSeenAt => 'last_seen_at';
  static String get c_lastLogin => 'last_login';

  static List<Profiles> converter(List<Map<String, dynamic>> data) {
    return data.map(Profiles.fromJson).toList();
  }

  static Profiles converterSingle(Map<String, dynamic> data) {
    return Profiles.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? firstName,
    String? lastName,
    DateTime? birthDate,
    bool? isTester,
    int? birthYear,
    bool? summarizationEnabled,
    String? email,
    String? phoneNumber,
    String? imageUrl,
    DateTime? lastSeenAt,
    DateTime? lastLogin,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (coachId != null) 'coach_id': coachId,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (sex != null) 'sex': sex,
      if (notificationSettings != null)
        'notification_settings': notificationSettings,
      if (moodConfig != null) 'mood_config': moodConfig,
      if (voiceEnabled != null) 'voice_enabled': voiceEnabled,
      if (languageCode != null) 'language_code': languageCode,
      if (timezone != null) 'timezone': timezone,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (coach != null) 'coach': coach,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (metadata != null) 'metadata': metadata,
      if (firstName != null) 'first_name': firstName,
      if (lastName != null) 'last_name': lastName,
      if (birthDate != null) 'birth_date': birthDate.toIso8601String(),
      if (isTester != null) 'is_tester': isTester,
      if (birthYear != null) 'birth_year': birthYear,
      if (summarizationEnabled != null)
        'summarization_enabled': summarizationEnabled,
      if (email != null) 'email': email,
      if (phoneNumber != null) 'phone_number': phoneNumber,
      if (imageUrl != null) 'image_url': imageUrl,
      if (lastSeenAt != null)
        'last_seen_at': lastSeenAt.toUtc().toIso8601String(),
      if (lastLogin != null) 'last_login': lastLogin.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? firstName,
    String? lastName,
    DateTime? birthDate,
    bool? isTester,
    int? birthYear,
    bool? summarizationEnabled,
    String? email,
    String? phoneNumber,
    String? imageUrl,
    DateTime? lastSeenAt,
    DateTime? lastLogin,
  }) {
    return _generateMap(
      id: id,
      name: name,
      coachId: coachId,
      yearOfBirth: yearOfBirth,
      sex: sex,
      notificationSettings: notificationSettings,
      moodConfig: moodConfig,
      voiceEnabled: voiceEnabled,
      languageCode: languageCode,
      timezone: timezone,
      createdAt: createdAt,
      updatedAt: updatedAt,
      coach: coach,
      avatarUrl: avatarUrl,
      metadata: metadata,
      firstName: firstName,
      lastName: lastName,
      birthDate: birthDate,
      isTester: isTester,
      birthYear: birthYear,
      summarizationEnabled: summarizationEnabled,
      email: email,
      phoneNumber: phoneNumber,
      imageUrl: imageUrl,
      lastSeenAt: lastSeenAt,
      lastLogin: lastLogin,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? firstName,
    String? lastName,
    DateTime? birthDate,
    bool? isTester,
    int? birthYear,
    bool? summarizationEnabled,
    String? email,
    String? phoneNumber,
    String? imageUrl,
    DateTime? lastSeenAt,
    DateTime? lastLogin,
  }) {
    return _generateMap(
      id: id,
      name: name,
      coachId: coachId,
      yearOfBirth: yearOfBirth,
      sex: sex,
      notificationSettings: notificationSettings,
      moodConfig: moodConfig,
      voiceEnabled: voiceEnabled,
      languageCode: languageCode,
      timezone: timezone,
      createdAt: createdAt,
      updatedAt: updatedAt,
      coach: coach,
      avatarUrl: avatarUrl,
      metadata: metadata,
      firstName: firstName,
      lastName: lastName,
      birthDate: birthDate,
      isTester: isTester,
      birthYear: birthYear,
      summarizationEnabled: summarizationEnabled,
      email: email,
      phoneNumber: phoneNumber,
      imageUrl: imageUrl,
      lastSeenAt: lastSeenAt,
      lastLogin: lastLogin,
    );
  }

  factory Profiles.fromJson(Map<String, dynamic> jsonn) {
    return Profiles(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      coachId: jsonn['coach_id'] != null ? jsonn['coach_id'].toString() : null,
      yearOfBirth: jsonn['year_of_birth'] != null
          ? int.parse(jsonn['year_of_birth'].toString())
          : null,
      sex: jsonn['sex'] != null ? jsonn['sex'].toString() : null,
      notificationSettings: jsonn['notification_settings'] != null
          ? jsonn['notification_settings'] as Map<String, dynamic>
          : null,
      moodConfig: jsonn['mood_config'] != null
          ? jsonn['mood_config'] as Map<String, dynamic>
          : null,
      voiceEnabled: jsonn['voice_enabled'] != null
          ? jsonn['voice_enabled'] as bool
          : null,
      languageCode: jsonn['language_code'] != null
          ? jsonn['language_code'].toString()
          : null,
      timezone: jsonn['timezone'] != null ? jsonn['timezone'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      coach: jsonn['coach'] != null
          ? jsonn['coach'] as Map<String, dynamic>
          : null,
      avatarUrl:
          jsonn['avatar_url'] != null ? jsonn['avatar_url'].toString() : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
      firstName:
          jsonn['first_name'] != null ? jsonn['first_name'].toString() : null,
      lastName:
          jsonn['last_name'] != null ? jsonn['last_name'].toString() : null,
      birthDate: jsonn['birth_date'] != null
          ? DateTime.parse(jsonn['birth_date'].toString())
          : null,
      isTester: jsonn['is_tester'] != null ? jsonn['is_tester'] as bool : null,
      birthYear: jsonn['birth_year'] != null
          ? int.parse(jsonn['birth_year'].toString())
          : null,
      summarizationEnabled: jsonn['summarization_enabled'] != null
          ? jsonn['summarization_enabled'] as bool
          : null,
      email: jsonn['email'] != null ? jsonn['email'].toString() : null,
      phoneNumber: jsonn['phone_number'] != null
          ? jsonn['phone_number'].toString()
          : null,
      imageUrl:
          jsonn['image_url'] != null ? jsonn['image_url'].toString() : null,
      lastSeenAt: jsonn['last_seen_at'] != null
          ? DateTime.parse(jsonn['last_seen_at'].toString())
          : null,
      lastLogin: jsonn['last_login'] != null
          ? DateTime.parse(jsonn['last_login'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? firstName,
    String? lastName,
    DateTime? birthDate,
    bool? isTester,
    int? birthYear,
    bool? summarizationEnabled,
    String? email,
    String? phoneNumber,
    String? imageUrl,
    DateTime? lastSeenAt,
    DateTime? lastLogin,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (coachId != null) 'coach_id': coachId,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (sex != null) 'sex': sex,
      if (notificationSettings != null)
        'notification_settings': notificationSettings,
      if (moodConfig != null) 'mood_config': moodConfig,
      if (voiceEnabled != null) 'voice_enabled': voiceEnabled,
      if (languageCode != null) 'language_code': languageCode,
      if (timezone != null) 'timezone': timezone,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (coach != null) 'coach': coach,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (metadata != null) 'metadata': metadata,
      if (firstName != null) 'first_name': firstName,
      if (lastName != null) 'last_name': lastName,
      if (birthDate != null) 'birth_date': birthDate,
      if (isTester != null) 'is_tester': isTester,
      if (birthYear != null) 'birth_year': birthYear,
      if (summarizationEnabled != null)
        'summarization_enabled': summarizationEnabled,
      if (email != null) 'email': email,
      if (phoneNumber != null) 'phone_number': phoneNumber,
      if (imageUrl != null) 'image_url': imageUrl,
      if (lastSeenAt != null) 'last_seen_at': lastSeenAt,
      if (lastLogin != null) 'last_login': lastLogin,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      name: name,
      coachId: coachId,
      yearOfBirth: yearOfBirth,
      sex: sex,
      notificationSettings: notificationSettings,
      moodConfig: moodConfig,
      voiceEnabled: voiceEnabled,
      languageCode: languageCode,
      timezone: timezone,
      createdAt: createdAt,
      updatedAt: updatedAt,
      coach: coach,
      avatarUrl: avatarUrl,
      metadata: metadata,
      firstName: firstName,
      lastName: lastName,
      birthDate: birthDate,
      isTester: isTester,
      birthYear: birthYear,
      summarizationEnabled: summarizationEnabled,
      email: email,
      phoneNumber: phoneNumber,
      imageUrl: imageUrl,
      lastSeenAt: lastSeenAt,
      lastLogin: lastLogin,
    );
  }

  static const _unset = Object();
  Profiles copyWith({
    Object? id = _unset,
    Object? name = _unset,
    Object? coachId = _unset,
    Object? yearOfBirth = _unset,
    Object? sex = _unset,
    Object? notificationSettings = _unset,
    Object? moodConfig = _unset,
    Object? voiceEnabled = _unset,
    Object? languageCode = _unset,
    Object? timezone = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? coach = _unset,
    Object? avatarUrl = _unset,
    Object? metadata = _unset,
    Object? firstName = _unset,
    Object? lastName = _unset,
    Object? birthDate = _unset,
    Object? isTester = _unset,
    Object? birthYear = _unset,
    Object? summarizationEnabled = _unset,
    Object? email = _unset,
    Object? phoneNumber = _unset,
    Object? imageUrl = _unset,
    Object? lastSeenAt = _unset,
    Object? lastLogin = _unset,
  }) {
    return Profiles(
      id: id == _unset ? this.id : id as String,
      name: name == _unset ? this.name : name as String?,
      coachId: coachId == _unset ? this.coachId : coachId as String?,
      yearOfBirth:
          yearOfBirth == _unset ? this.yearOfBirth : yearOfBirth as int?,
      sex: sex == _unset ? this.sex : sex as String?,
      notificationSettings: notificationSettings == _unset
          ? this.notificationSettings
          : notificationSettings as Map<String, dynamic>?,
      moodConfig: moodConfig == _unset
          ? this.moodConfig
          : moodConfig as Map<String, dynamic>?,
      voiceEnabled:
          voiceEnabled == _unset ? this.voiceEnabled : voiceEnabled as bool?,
      languageCode:
          languageCode == _unset ? this.languageCode : languageCode as String?,
      timezone: timezone == _unset ? this.timezone : timezone as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      coach: coach == _unset ? this.coach : coach as Map<String, dynamic>?,
      avatarUrl: avatarUrl == _unset ? this.avatarUrl : avatarUrl as String?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
      firstName: firstName == _unset ? this.firstName : firstName as String?,
      lastName: lastName == _unset ? this.lastName : lastName as String?,
      birthDate: birthDate == _unset ? this.birthDate : birthDate as DateTime?,
      isTester: isTester == _unset ? this.isTester : isTester as bool?,
      birthYear: birthYear == _unset ? this.birthYear : birthYear as int?,
      summarizationEnabled: summarizationEnabled == _unset
          ? this.summarizationEnabled
          : summarizationEnabled as bool?,
      email: email == _unset ? this.email : email as String?,
      phoneNumber:
          phoneNumber == _unset ? this.phoneNumber : phoneNumber as String?,
      imageUrl: imageUrl == _unset ? this.imageUrl : imageUrl as String?,
      lastSeenAt:
          lastSeenAt == _unset ? this.lastSeenAt : lastSeenAt as DateTime?,
      lastLogin: lastLogin == _unset ? this.lastLogin : lastLogin as DateTime?,
    );
  }
}
