// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class UserStats implements SupadartClass<UserStats> {
  final String? userId;
  final BigInt? totalMessages;
  final BigInt? totalCheckins;
  final BigInt? categoriesUsed;
  final BigInt? favoriteCategories;
  final BigInt? completedCheckins;
  final BigInt? activeCards;
  final DateTime? lastActivity;

  const UserStats({
    this.userId,
    this.totalMessages,
    this.totalCheckins,
    this.categoriesUsed,
    this.favoriteCategories,
    this.completedCheckins,
    this.activeCards,
    this.lastActivity,
  });

  static String get table_name => 'user_stats';
  static String get c_userId => 'user_id';
  static String get c_totalMessages => 'total_messages';
  static String get c_totalCheckins => 'total_checkins';
  static String get c_categoriesUsed => 'categories_used';
  static String get c_favoriteCategories => 'favorite_categories';
  static String get c_completedCheckins => 'completed_checkins';
  static String get c_activeCards => 'active_cards';
  static String get c_lastActivity => 'last_activity';

  static List<UserStats> converter(List<Map<String, dynamic>> data) {
    return data.map(UserStats.fromJson).toList();
  }

  static UserStats converterSingle(Map<String, dynamic> data) {
    return UserStats.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? userId,
    BigInt? totalMessages,
    BigInt? totalCheckins,
    BigInt? categoriesUsed,
    BigInt? favoriteCategories,
    BigInt? completedCheckins,
    BigInt? activeCards,
    DateTime? lastActivity,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (totalMessages != null) 'total_messages': totalMessages.toString(),
      if (totalCheckins != null) 'total_checkins': totalCheckins.toString(),
      if (categoriesUsed != null) 'categories_used': categoriesUsed.toString(),
      if (favoriteCategories != null)
        'favorite_categories': favoriteCategories.toString(),
      if (completedCheckins != null)
        'completed_checkins': completedCheckins.toString(),
      if (activeCards != null) 'active_cards': activeCards.toString(),
      if (lastActivity != null)
        'last_activity': lastActivity.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? userId,
    BigInt? totalMessages,
    BigInt? totalCheckins,
    BigInt? categoriesUsed,
    BigInt? favoriteCategories,
    BigInt? completedCheckins,
    BigInt? activeCards,
    DateTime? lastActivity,
  }) {
    return _generateMap(
      userId: userId,
      totalMessages: totalMessages,
      totalCheckins: totalCheckins,
      categoriesUsed: categoriesUsed,
      favoriteCategories: favoriteCategories,
      completedCheckins: completedCheckins,
      activeCards: activeCards,
      lastActivity: lastActivity,
    );
  }

  static Map<String, dynamic> update({
    String? userId,
    BigInt? totalMessages,
    BigInt? totalCheckins,
    BigInt? categoriesUsed,
    BigInt? favoriteCategories,
    BigInt? completedCheckins,
    BigInt? activeCards,
    DateTime? lastActivity,
  }) {
    return _generateMap(
      userId: userId,
      totalMessages: totalMessages,
      totalCheckins: totalCheckins,
      categoriesUsed: categoriesUsed,
      favoriteCategories: favoriteCategories,
      completedCheckins: completedCheckins,
      activeCards: activeCards,
      lastActivity: lastActivity,
    );
  }

  factory UserStats.fromJson(Map<String, dynamic> jsonn) {
    return UserStats(
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      totalMessages: jsonn['total_messages'] != null
          ? BigInt.parse(jsonn['total_messages'].toString())
          : null,
      totalCheckins: jsonn['total_checkins'] != null
          ? BigInt.parse(jsonn['total_checkins'].toString())
          : null,
      categoriesUsed: jsonn['categories_used'] != null
          ? BigInt.parse(jsonn['categories_used'].toString())
          : null,
      favoriteCategories: jsonn['favorite_categories'] != null
          ? BigInt.parse(jsonn['favorite_categories'].toString())
          : null,
      completedCheckins: jsonn['completed_checkins'] != null
          ? BigInt.parse(jsonn['completed_checkins'].toString())
          : null,
      activeCards: jsonn['active_cards'] != null
          ? BigInt.parse(jsonn['active_cards'].toString())
          : null,
      lastActivity: jsonn['last_activity'] != null
          ? DateTime.parse(jsonn['last_activity'].toString())
          : null,
    );
  }

  static Object New({
    String? userId,
    BigInt? totalMessages,
    BigInt? totalCheckins,
    BigInt? categoriesUsed,
    BigInt? favoriteCategories,
    BigInt? completedCheckins,
    BigInt? activeCards,
    DateTime? lastActivity,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (totalMessages != null) 'total_messages': totalMessages,
      if (totalCheckins != null) 'total_checkins': totalCheckins,
      if (categoriesUsed != null) 'categories_used': categoriesUsed,
      if (favoriteCategories != null) 'favorite_categories': favoriteCategories,
      if (completedCheckins != null) 'completed_checkins': completedCheckins,
      if (activeCards != null) 'active_cards': activeCards,
      if (lastActivity != null) 'last_activity': lastActivity,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      userId: userId,
      totalMessages: totalMessages,
      totalCheckins: totalCheckins,
      categoriesUsed: categoriesUsed,
      favoriteCategories: favoriteCategories,
      completedCheckins: completedCheckins,
      activeCards: activeCards,
      lastActivity: lastActivity,
    );
  }

  static const _unset = Object();
  UserStats copyWith({
    Object? userId = _unset,
    Object? totalMessages = _unset,
    Object? totalCheckins = _unset,
    Object? categoriesUsed = _unset,
    Object? favoriteCategories = _unset,
    Object? completedCheckins = _unset,
    Object? activeCards = _unset,
    Object? lastActivity = _unset,
  }) {
    return UserStats(
      userId: userId == _unset ? this.userId : userId as String?,
      totalMessages: totalMessages == _unset
          ? this.totalMessages
          : totalMessages as BigInt?,
      totalCheckins: totalCheckins == _unset
          ? this.totalCheckins
          : totalCheckins as BigInt?,
      categoriesUsed: categoriesUsed == _unset
          ? this.categoriesUsed
          : categoriesUsed as BigInt?,
      favoriteCategories: favoriteCategories == _unset
          ? this.favoriteCategories
          : favoriteCategories as BigInt?,
      completedCheckins: completedCheckins == _unset
          ? this.completedCheckins
          : completedCheckins as BigInt?,
      activeCards:
          activeCards == _unset ? this.activeCards : activeCards as BigInt?,
      lastActivity: lastActivity == _unset
          ? this.lastActivity
          : lastActivity as DateTime?,
    );
  }
}
