// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Coaches implements SupadartClass<Coaches> {
  final String id;
  final String name;
  final String? bio;
  final String? photoUrl;
  final String? sex;
  final int? yearOfBirth;
  final String? voiceId;
  final Map<String, dynamic>? voiceSettings;
  final String? prompt;
  final bool? isActive;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String? imageUrl;
  final Map<String, dynamic>? avatarSizes;
  final Map<String, dynamic>? metadata;
  final String? voice;
  final String? imageSmallUrl;
  final String? imageMediumUrl;
  final String? imageLargeUrl;
  final String? systemPrompt;

  const Coaches({
    required this.id,
    required this.name,
    this.bio,
    this.photoUrl,
    this.sex,
    this.yearOfBirth,
    this.voiceId,
    this.voiceSettings,
    this.prompt,
    this.isActive,
    this.createdAt,
    this.updatedAt,
    this.imageUrl,
    this.avatarSizes,
    this.metadata,
    this.voice,
    this.imageSmallUrl,
    this.imageMediumUrl,
    this.imageLargeUrl,
    this.systemPrompt,
  });

  static String get table_name => 'coaches';
  static String get c_id => 'id';
  static String get c_name => 'name';
  static String get c_bio => 'bio';
  static String get c_photoUrl => 'photo_url';
  static String get c_sex => 'sex';
  static String get c_yearOfBirth => 'year_of_birth';
  static String get c_voiceId => 'voice_id';
  static String get c_voiceSettings => 'voice_settings';
  static String get c_prompt => 'prompt';
  static String get c_isActive => 'is_active';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_imageUrl => 'image_url';
  static String get c_avatarSizes => 'avatar_sizes';
  static String get c_metadata => 'metadata';
  static String get c_voice => 'voice';
  static String get c_imageSmallUrl => 'image_small_url';
  static String get c_imageMediumUrl => 'image_medium_url';
  static String get c_imageLargeUrl => 'image_large_url';
  static String get c_systemPrompt => 'system_prompt';

  static List<Coaches> converter(List<Map<String, dynamic>> data) {
    return data.map(Coaches.fromJson).toList();
  }

  static Coaches converterSingle(Map<String, dynamic> data) {
    return Coaches.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? name,
    String? bio,
    String? photoUrl,
    String? sex,
    int? yearOfBirth,
    String? voiceId,
    Map<String, dynamic>? voiceSettings,
    String? prompt,
    bool? isActive,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? imageUrl,
    Map<String, dynamic>? avatarSizes,
    Map<String, dynamic>? metadata,
    String? voice,
    String? imageSmallUrl,
    String? imageMediumUrl,
    String? imageLargeUrl,
    String? systemPrompt,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (bio != null) 'bio': bio,
      if (photoUrl != null) 'photo_url': photoUrl,
      if (sex != null) 'sex': sex,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (voiceId != null) 'voice_id': voiceId,
      if (voiceSettings != null) 'voice_settings': voiceSettings,
      if (prompt != null) 'prompt': prompt,
      if (isActive != null) 'is_active': isActive,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (imageUrl != null) 'image_url': imageUrl,
      if (avatarSizes != null) 'avatar_sizes': avatarSizes,
      if (metadata != null) 'metadata': metadata,
      if (voice != null) 'voice': voice,
      if (imageSmallUrl != null) 'image_small_url': imageSmallUrl,
      if (imageMediumUrl != null) 'image_medium_url': imageMediumUrl,
      if (imageLargeUrl != null) 'image_large_url': imageLargeUrl,
      if (systemPrompt != null) 'system_prompt': systemPrompt,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String name,
    String? bio,
    String? photoUrl,
    String? sex,
    int? yearOfBirth,
    String? voiceId,
    Map<String, dynamic>? voiceSettings,
    String? prompt,
    bool? isActive,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? imageUrl,
    Map<String, dynamic>? avatarSizes,
    Map<String, dynamic>? metadata,
    String? voice,
    String? imageSmallUrl,
    String? imageMediumUrl,
    String? imageLargeUrl,
    String? systemPrompt,
  }) {
    return _generateMap(
      id: id,
      name: name,
      bio: bio,
      photoUrl: photoUrl,
      sex: sex,
      yearOfBirth: yearOfBirth,
      voiceId: voiceId,
      voiceSettings: voiceSettings,
      prompt: prompt,
      isActive: isActive,
      createdAt: createdAt,
      updatedAt: updatedAt,
      imageUrl: imageUrl,
      avatarSizes: avatarSizes,
      metadata: metadata,
      voice: voice,
      imageSmallUrl: imageSmallUrl,
      imageMediumUrl: imageMediumUrl,
      imageLargeUrl: imageLargeUrl,
      systemPrompt: systemPrompt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? name,
    String? bio,
    String? photoUrl,
    String? sex,
    int? yearOfBirth,
    String? voiceId,
    Map<String, dynamic>? voiceSettings,
    String? prompt,
    bool? isActive,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? imageUrl,
    Map<String, dynamic>? avatarSizes,
    Map<String, dynamic>? metadata,
    String? voice,
    String? imageSmallUrl,
    String? imageMediumUrl,
    String? imageLargeUrl,
    String? systemPrompt,
  }) {
    return _generateMap(
      id: id,
      name: name,
      bio: bio,
      photoUrl: photoUrl,
      sex: sex,
      yearOfBirth: yearOfBirth,
      voiceId: voiceId,
      voiceSettings: voiceSettings,
      prompt: prompt,
      isActive: isActive,
      createdAt: createdAt,
      updatedAt: updatedAt,
      imageUrl: imageUrl,
      avatarSizes: avatarSizes,
      metadata: metadata,
      voice: voice,
      imageSmallUrl: imageSmallUrl,
      imageMediumUrl: imageMediumUrl,
      imageLargeUrl: imageLargeUrl,
      systemPrompt: systemPrompt,
    );
  }

  factory Coaches.fromJson(Map<String, dynamic> jsonn) {
    return Coaches(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
      bio: jsonn['bio'] != null ? jsonn['bio'].toString() : null,
      photoUrl:
          jsonn['photo_url'] != null ? jsonn['photo_url'].toString() : null,
      sex: jsonn['sex'] != null ? jsonn['sex'].toString() : null,
      yearOfBirth: jsonn['year_of_birth'] != null
          ? int.parse(jsonn['year_of_birth'].toString())
          : null,
      voiceId: jsonn['voice_id'] != null ? jsonn['voice_id'].toString() : null,
      voiceSettings: jsonn['voice_settings'] != null
          ? jsonn['voice_settings'] as Map<String, dynamic>
          : null,
      prompt: jsonn['prompt'] != null ? jsonn['prompt'].toString() : null,
      isActive: jsonn['is_active'] != null ? jsonn['is_active'] as bool : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      imageUrl:
          jsonn['image_url'] != null ? jsonn['image_url'].toString() : null,
      avatarSizes: jsonn['avatar_sizes'] != null
          ? jsonn['avatar_sizes'] as Map<String, dynamic>
          : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
      voice: jsonn['voice'] != null ? jsonn['voice'].toString() : null,
      imageSmallUrl: jsonn['image_small_url'] != null
          ? jsonn['image_small_url'].toString()
          : null,
      imageMediumUrl: jsonn['image_medium_url'] != null
          ? jsonn['image_medium_url'].toString()
          : null,
      imageLargeUrl: jsonn['image_large_url'] != null
          ? jsonn['image_large_url'].toString()
          : null,
      systemPrompt: jsonn['system_prompt'] != null
          ? jsonn['system_prompt'].toString()
          : null,
    );
  }

  static Object New({
    String? id,
    String? name,
    String? bio,
    String? photoUrl,
    String? sex,
    int? yearOfBirth,
    String? voiceId,
    Map<String, dynamic>? voiceSettings,
    String? prompt,
    bool? isActive,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? imageUrl,
    Map<String, dynamic>? avatarSizes,
    Map<String, dynamic>? metadata,
    String? voice,
    String? imageSmallUrl,
    String? imageMediumUrl,
    String? imageLargeUrl,
    String? systemPrompt,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (bio != null) 'bio': bio,
      if (photoUrl != null) 'photo_url': photoUrl,
      if (sex != null) 'sex': sex,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (voiceId != null) 'voice_id': voiceId,
      if (voiceSettings != null) 'voice_settings': voiceSettings,
      if (prompt != null) 'prompt': prompt,
      if (isActive != null) 'is_active': isActive,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (imageUrl != null) 'image_url': imageUrl,
      if (avatarSizes != null) 'avatar_sizes': avatarSizes,
      if (metadata != null) 'metadata': metadata,
      if (voice != null) 'voice': voice,
      if (imageSmallUrl != null) 'image_small_url': imageSmallUrl,
      if (imageMediumUrl != null) 'image_medium_url': imageMediumUrl,
      if (imageLargeUrl != null) 'image_large_url': imageLargeUrl,
      if (systemPrompt != null) 'system_prompt': systemPrompt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      name: name,
      bio: bio,
      photoUrl: photoUrl,
      sex: sex,
      yearOfBirth: yearOfBirth,
      voiceId: voiceId,
      voiceSettings: voiceSettings,
      prompt: prompt,
      isActive: isActive,
      createdAt: createdAt,
      updatedAt: updatedAt,
      imageUrl: imageUrl,
      avatarSizes: avatarSizes,
      metadata: metadata,
      voice: voice,
      imageSmallUrl: imageSmallUrl,
      imageMediumUrl: imageMediumUrl,
      imageLargeUrl: imageLargeUrl,
      systemPrompt: systemPrompt,
    );
  }

  static const _unset = Object();
  Coaches copyWith({
    Object? id = _unset,
    Object? name = _unset,
    Object? bio = _unset,
    Object? photoUrl = _unset,
    Object? sex = _unset,
    Object? yearOfBirth = _unset,
    Object? voiceId = _unset,
    Object? voiceSettings = _unset,
    Object? prompt = _unset,
    Object? isActive = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? imageUrl = _unset,
    Object? avatarSizes = _unset,
    Object? metadata = _unset,
    Object? voice = _unset,
    Object? imageSmallUrl = _unset,
    Object? imageMediumUrl = _unset,
    Object? imageLargeUrl = _unset,
    Object? systemPrompt = _unset,
  }) {
    return Coaches(
      id: id == _unset ? this.id : id as String,
      name: name == _unset ? this.name : name as String,
      bio: bio == _unset ? this.bio : bio as String?,
      photoUrl: photoUrl == _unset ? this.photoUrl : photoUrl as String?,
      sex: sex == _unset ? this.sex : sex as String?,
      yearOfBirth:
          yearOfBirth == _unset ? this.yearOfBirth : yearOfBirth as int?,
      voiceId: voiceId == _unset ? this.voiceId : voiceId as String?,
      voiceSettings: voiceSettings == _unset
          ? this.voiceSettings
          : voiceSettings as Map<String, dynamic>?,
      prompt: prompt == _unset ? this.prompt : prompt as String?,
      isActive: isActive == _unset ? this.isActive : isActive as bool?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      imageUrl: imageUrl == _unset ? this.imageUrl : imageUrl as String?,
      avatarSizes: avatarSizes == _unset
          ? this.avatarSizes
          : avatarSizes as Map<String, dynamic>?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
      voice: voice == _unset ? this.voice : voice as String?,
      imageSmallUrl: imageSmallUrl == _unset
          ? this.imageSmallUrl
          : imageSmallUrl as String?,
      imageMediumUrl: imageMediumUrl == _unset
          ? this.imageMediumUrl
          : imageMediumUrl as String?,
      imageLargeUrl: imageLargeUrl == _unset
          ? this.imageLargeUrl
          : imageLargeUrl as String?,
      systemPrompt:
          systemPrompt == _unset ? this.systemPrompt : systemPrompt as String?,
    );
  }
}
