// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class CheckIns implements SupadartClass<CheckIns> {
  final String id;
  final String userId;
  final String? categoryId;
  final String? status;
  final Map<String, dynamic> questions;
  final String? summary;
  final String? insight;
  final String? brief;
  final int? level;
  final DateTime? createdAt;
  final DateTime? completedAt;

  const CheckIns({
    required this.id,
    required this.userId,
    this.categoryId,
    this.status,
    required this.questions,
    this.summary,
    this.insight,
    this.brief,
    this.level,
    this.createdAt,
    this.completedAt,
  });

  static String get table_name => 'check_ins';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_categoryId => 'category_id';
  static String get c_status => 'status';
  static String get c_questions => 'questions';
  static String get c_summary => 'summary';
  static String get c_insight => 'insight';
  static String get c_brief => 'brief';
  static String get c_level => 'level';
  static String get c_createdAt => 'created_at';
  static String get c_completedAt => 'completed_at';

  static List<CheckIns> converter(List<Map<String, dynamic>> data) {
    return data.map(CheckIns.fromJson).toList();
  }

  static CheckIns converterSingle(Map<String, dynamic> data) {
    return CheckIns.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? categoryId,
    String? status,
    Map<String, dynamic>? questions,
    String? summary,
    String? insight,
    String? brief,
    int? level,
    DateTime? createdAt,
    DateTime? completedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (status != null) 'status': status,
      if (questions != null) 'questions': questions,
      if (summary != null) 'summary': summary,
      if (insight != null) 'insight': insight,
      if (brief != null) 'brief': brief,
      if (level != null) 'level': level,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (completedAt != null)
        'completed_at': completedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String userId,
    String? categoryId,
    String? status,
    required Map<String, dynamic> questions,
    String? summary,
    String? insight,
    String? brief,
    int? level,
    DateTime? createdAt,
    DateTime? completedAt,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      status: status,
      questions: questions,
      summary: summary,
      insight: insight,
      brief: brief,
      level: level,
      createdAt: createdAt,
      completedAt: completedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? categoryId,
    String? status,
    Map<String, dynamic>? questions,
    String? summary,
    String? insight,
    String? brief,
    int? level,
    DateTime? createdAt,
    DateTime? completedAt,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      status: status,
      questions: questions,
      summary: summary,
      insight: insight,
      brief: brief,
      level: level,
      createdAt: createdAt,
      completedAt: completedAt,
    );
  }

  factory CheckIns.fromJson(Map<String, dynamic> jsonn) {
    return CheckIns(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      categoryId:
          jsonn['category_id'] != null ? jsonn['category_id'].toString() : null,
      status: jsonn['status'] != null ? jsonn['status'].toString() : null,
      questions: jsonn['questions'] != null
          ? jsonn['questions'] as Map<String, dynamic>
          : <String, dynamic>{},
      summary: jsonn['summary'] != null ? jsonn['summary'].toString() : null,
      insight: jsonn['insight'] != null ? jsonn['insight'].toString() : null,
      brief: jsonn['brief'] != null ? jsonn['brief'].toString() : null,
      level:
          jsonn['level'] != null ? int.parse(jsonn['level'].toString()) : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      completedAt: jsonn['completed_at'] != null
          ? DateTime.parse(jsonn['completed_at'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? categoryId,
    String? status,
    Map<String, dynamic>? questions,
    String? summary,
    String? insight,
    String? brief,
    int? level,
    DateTime? createdAt,
    DateTime? completedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (status != null) 'status': status,
      if (questions != null) 'questions': questions,
      if (summary != null) 'summary': summary,
      if (insight != null) 'insight': insight,
      if (brief != null) 'brief': brief,
      if (level != null) 'level': level,
      if (createdAt != null) 'created_at': createdAt,
      if (completedAt != null) 'completed_at': completedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      status: status,
      questions: questions,
      summary: summary,
      insight: insight,
      brief: brief,
      level: level,
      createdAt: createdAt,
      completedAt: completedAt,
    );
  }

  static const _unset = Object();
  CheckIns copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? categoryId = _unset,
    Object? status = _unset,
    Object? questions = _unset,
    Object? summary = _unset,
    Object? insight = _unset,
    Object? brief = _unset,
    Object? level = _unset,
    Object? createdAt = _unset,
    Object? completedAt = _unset,
  }) {
    return CheckIns(
      id: id == _unset ? this.id : id as String,
      userId: userId == _unset ? this.userId : userId as String,
      categoryId:
          categoryId == _unset ? this.categoryId : categoryId as String?,
      status: status == _unset ? this.status : status as String?,
      questions: questions == _unset
          ? this.questions
          : questions as Map<String, dynamic>,
      summary: summary == _unset ? this.summary : summary as String?,
      insight: insight == _unset ? this.insight : insight as String?,
      brief: brief == _unset ? this.brief : brief as String?,
      level: level == _unset ? this.level : level as int?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      completedAt:
          completedAt == _unset ? this.completedAt : completedAt as DateTime?,
    );
  }
}
