// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class SystemLogs implements SupadartClass<SystemLogs> {
  final String id;
  final String eventType;
  final Map<String, dynamic>? eventData;
  final DateTime? createdAt;
  final String? createdBy;

  const SystemLogs({
    required this.id,
    required this.eventType,
    this.eventData,
    this.createdAt,
    this.createdBy,
  });

  static String get table_name => 'system_logs';
  static String get c_id => 'id';
  static String get c_eventType => 'event_type';
  static String get c_eventData => 'event_data';
  static String get c_createdAt => 'created_at';
  static String get c_createdBy => 'created_by';

  static List<SystemLogs> converter(List<Map<String, dynamic>> data) {
    return data.map(SystemLogs.fromJson).toList();
  }

  static SystemLogs converterSingle(Map<String, dynamic> data) {
    return SystemLogs.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? eventType,
    Map<String, dynamic>? eventData,
    DateTime? createdAt,
    String? createdBy,
  }) {
    return {
      if (id != null) 'id': id,
      if (eventType != null) 'event_type': eventType,
      if (eventData != null) 'event_data': eventData,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (createdBy != null) 'created_by': createdBy,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String eventType,
    Map<String, dynamic>? eventData,
    DateTime? createdAt,
    String? createdBy,
  }) {
    return _generateMap(
      id: id,
      eventType: eventType,
      eventData: eventData,
      createdAt: createdAt,
      createdBy: createdBy,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? eventType,
    Map<String, dynamic>? eventData,
    DateTime? createdAt,
    String? createdBy,
  }) {
    return _generateMap(
      id: id,
      eventType: eventType,
      eventData: eventData,
      createdAt: createdAt,
      createdBy: createdBy,
    );
  }

  factory SystemLogs.fromJson(Map<String, dynamic> jsonn) {
    return SystemLogs(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      eventType:
          jsonn['event_type'] != null ? jsonn['event_type'].toString() : '',
      eventData: jsonn['event_data'] != null
          ? jsonn['event_data'] as Map<String, dynamic>
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      createdBy:
          jsonn['created_by'] != null ? jsonn['created_by'].toString() : null,
    );
  }

  static Object New({
    String? id,
    String? eventType,
    Map<String, dynamic>? eventData,
    DateTime? createdAt,
    String? createdBy,
  }) {
    return {
      if (id != null) 'id': id,
      if (eventType != null) 'event_type': eventType,
      if (eventData != null) 'event_data': eventData,
      if (createdAt != null) 'created_at': createdAt,
      if (createdBy != null) 'created_by': createdBy,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      eventType: eventType,
      eventData: eventData,
      createdAt: createdAt,
      createdBy: createdBy,
    );
  }

  static const _unset = Object();
  SystemLogs copyWith({
    Object? id = _unset,
    Object? eventType = _unset,
    Object? eventData = _unset,
    Object? createdAt = _unset,
    Object? createdBy = _unset,
  }) {
    return SystemLogs(
      id: id == _unset ? this.id : id as String,
      eventType: eventType == _unset ? this.eventType : eventType as String,
      eventData: eventData == _unset
          ? this.eventData
          : eventData as Map<String, dynamic>?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      createdBy: createdBy == _unset ? this.createdBy : createdBy as String?,
    );
  }
}
