// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class UserProfilesNormalized implements SupadartClass<UserProfilesNormalized> {
  final String? userId;
  final String? id;
  final String? name;
  final String? email;
  final String? phoneNumber;
  final int? yearOfBirth;
  final int? birthYear;
  final String? gender;
  final String? genderRaw;
  final String? coachId;
  final String? imageUrl;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final Map<String, dynamic>? metadata;

  const UserProfilesNormalized({
    this.userId,
    this.id,
    this.name,
    this.email,
    this.phoneNumber,
    this.yearOfBirth,
    this.birthYear,
    this.gender,
    this.genderRaw,
    this.coachId,
    this.imageUrl,
    this.createdAt,
    this.updatedAt,
    this.metadata,
  });

  static String get table_name => 'user_profiles_normalized';
  static String get c_userId => 'user_id';
  static String get c_id => 'id';
  static String get c_name => 'name';
  static String get c_email => 'email';
  static String get c_phoneNumber => 'phone_number';
  static String get c_yearOfBirth => 'year_of_birth';
  static String get c_birthYear => 'birth_year';
  static String get c_gender => 'gender';
  static String get c_genderRaw => 'gender_raw';
  static String get c_coachId => 'coach_id';
  static String get c_imageUrl => 'image_url';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_metadata => 'metadata';

  static List<UserProfilesNormalized> converter(
      List<Map<String, dynamic>> data) {
    return data.map(UserProfilesNormalized.fromJson).toList();
  }

  static UserProfilesNormalized converterSingle(Map<String, dynamic> data) {
    return UserProfilesNormalized.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? userId,
    String? id,
    String? name,
    String? email,
    String? phoneNumber,
    int? yearOfBirth,
    int? birthYear,
    String? gender,
    String? genderRaw,
    String? coachId,
    String? imageUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (email != null) 'email': email,
      if (phoneNumber != null) 'phone_number': phoneNumber,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (birthYear != null) 'birth_year': birthYear,
      if (gender != null) 'gender': gender,
      if (genderRaw != null) 'gender_raw': genderRaw,
      if (coachId != null) 'coach_id': coachId,
      if (imageUrl != null) 'image_url': imageUrl,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (metadata != null) 'metadata': metadata,
    };
  }

  static Map<String, dynamic> insert({
    String? userId,
    String? id,
    String? name,
    String? email,
    String? phoneNumber,
    int? yearOfBirth,
    int? birthYear,
    String? gender,
    String? genderRaw,
    String? coachId,
    String? imageUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
  }) {
    return _generateMap(
      userId: userId,
      id: id,
      name: name,
      email: email,
      phoneNumber: phoneNumber,
      yearOfBirth: yearOfBirth,
      birthYear: birthYear,
      gender: gender,
      genderRaw: genderRaw,
      coachId: coachId,
      imageUrl: imageUrl,
      createdAt: createdAt,
      updatedAt: updatedAt,
      metadata: metadata,
    );
  }

  static Map<String, dynamic> update({
    String? userId,
    String? id,
    String? name,
    String? email,
    String? phoneNumber,
    int? yearOfBirth,
    int? birthYear,
    String? gender,
    String? genderRaw,
    String? coachId,
    String? imageUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
  }) {
    return _generateMap(
      userId: userId,
      id: id,
      name: name,
      email: email,
      phoneNumber: phoneNumber,
      yearOfBirth: yearOfBirth,
      birthYear: birthYear,
      gender: gender,
      genderRaw: genderRaw,
      coachId: coachId,
      imageUrl: imageUrl,
      createdAt: createdAt,
      updatedAt: updatedAt,
      metadata: metadata,
    );
  }

  factory UserProfilesNormalized.fromJson(Map<String, dynamic> jsonn) {
    return UserProfilesNormalized(
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      email: jsonn['email'] != null ? jsonn['email'].toString() : null,
      phoneNumber: jsonn['phone_number'] != null
          ? jsonn['phone_number'].toString()
          : null,
      yearOfBirth: jsonn['year_of_birth'] != null
          ? int.parse(jsonn['year_of_birth'].toString())
          : null,
      birthYear: jsonn['birth_year'] != null
          ? int.parse(jsonn['birth_year'].toString())
          : null,
      gender: jsonn['gender'] != null ? jsonn['gender'].toString() : null,
      genderRaw:
          jsonn['gender_raw'] != null ? jsonn['gender_raw'].toString() : null,
      coachId: jsonn['coach_id'] != null ? jsonn['coach_id'].toString() : null,
      imageUrl:
          jsonn['image_url'] != null ? jsonn['image_url'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
    );
  }

  static Object New({
    String? userId,
    String? id,
    String? name,
    String? email,
    String? phoneNumber,
    int? yearOfBirth,
    int? birthYear,
    String? gender,
    String? genderRaw,
    String? coachId,
    String? imageUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (email != null) 'email': email,
      if (phoneNumber != null) 'phone_number': phoneNumber,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (birthYear != null) 'birth_year': birthYear,
      if (gender != null) 'gender': gender,
      if (genderRaw != null) 'gender_raw': genderRaw,
      if (coachId != null) 'coach_id': coachId,
      if (imageUrl != null) 'image_url': imageUrl,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (metadata != null) 'metadata': metadata,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      userId: userId,
      id: id,
      name: name,
      email: email,
      phoneNumber: phoneNumber,
      yearOfBirth: yearOfBirth,
      birthYear: birthYear,
      gender: gender,
      genderRaw: genderRaw,
      coachId: coachId,
      imageUrl: imageUrl,
      createdAt: createdAt,
      updatedAt: updatedAt,
      metadata: metadata,
    );
  }

  static const _unset = Object();
  UserProfilesNormalized copyWith({
    Object? userId = _unset,
    Object? id = _unset,
    Object? name = _unset,
    Object? email = _unset,
    Object? phoneNumber = _unset,
    Object? yearOfBirth = _unset,
    Object? birthYear = _unset,
    Object? gender = _unset,
    Object? genderRaw = _unset,
    Object? coachId = _unset,
    Object? imageUrl = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? metadata = _unset,
  }) {
    return UserProfilesNormalized(
      userId: userId == _unset ? this.userId : userId as String?,
      id: id == _unset ? this.id : id as String?,
      name: name == _unset ? this.name : name as String?,
      email: email == _unset ? this.email : email as String?,
      phoneNumber:
          phoneNumber == _unset ? this.phoneNumber : phoneNumber as String?,
      yearOfBirth:
          yearOfBirth == _unset ? this.yearOfBirth : yearOfBirth as int?,
      birthYear: birthYear == _unset ? this.birthYear : birthYear as int?,
      gender: gender == _unset ? this.gender : gender as String?,
      genderRaw: genderRaw == _unset ? this.genderRaw : genderRaw as String?,
      coachId: coachId == _unset ? this.coachId : coachId as String?,
      imageUrl: imageUrl == _unset ? this.imageUrl : imageUrl as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
    );
  }
}
