// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class AnalyticsEvents implements SupadartClass<AnalyticsEvents> {
  final String id;
  final String? userId;
  final String? sessionId;
  final String eventName;
  final String? eventCategory;
  final Map<String, dynamic>? eventProperties;
  final String? platform;
  final String? appVersion;
  final Map<String, dynamic>? deviceInfo;
  final DateTime? createdAt;

  const AnalyticsEvents({
    required this.id,
    this.userId,
    this.sessionId,
    required this.eventName,
    this.eventCategory,
    this.eventProperties,
    this.platform,
    this.appVersion,
    this.deviceInfo,
    this.createdAt,
  });

  static String get table_name => 'analytics_events';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_sessionId => 'session_id';
  static String get c_eventName => 'event_name';
  static String get c_eventCategory => 'event_category';
  static String get c_eventProperties => 'event_properties';
  static String get c_platform => 'platform';
  static String get c_appVersion => 'app_version';
  static String get c_deviceInfo => 'device_info';
  static String get c_createdAt => 'created_at';

  static List<AnalyticsEvents> converter(List<Map<String, dynamic>> data) {
    return data.map(AnalyticsEvents.fromJson).toList();
  }

  static AnalyticsEvents converterSingle(Map<String, dynamic> data) {
    return AnalyticsEvents.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? sessionId,
    String? eventName,
    String? eventCategory,
    Map<String, dynamic>? eventProperties,
    String? platform,
    String? appVersion,
    Map<String, dynamic>? deviceInfo,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (sessionId != null) 'session_id': sessionId,
      if (eventName != null) 'event_name': eventName,
      if (eventCategory != null) 'event_category': eventCategory,
      if (eventProperties != null) 'event_properties': eventProperties,
      if (platform != null) 'platform': platform,
      if (appVersion != null) 'app_version': appVersion,
      if (deviceInfo != null) 'device_info': deviceInfo,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? userId,
    String? sessionId,
    required String eventName,
    String? eventCategory,
    Map<String, dynamic>? eventProperties,
    String? platform,
    String? appVersion,
    Map<String, dynamic>? deviceInfo,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      sessionId: sessionId,
      eventName: eventName,
      eventCategory: eventCategory,
      eventProperties: eventProperties,
      platform: platform,
      appVersion: appVersion,
      deviceInfo: deviceInfo,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? sessionId,
    String? eventName,
    String? eventCategory,
    Map<String, dynamic>? eventProperties,
    String? platform,
    String? appVersion,
    Map<String, dynamic>? deviceInfo,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      sessionId: sessionId,
      eventName: eventName,
      eventCategory: eventCategory,
      eventProperties: eventProperties,
      platform: platform,
      appVersion: appVersion,
      deviceInfo: deviceInfo,
      createdAt: createdAt,
    );
  }

  factory AnalyticsEvents.fromJson(Map<String, dynamic> jsonn) {
    return AnalyticsEvents(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      sessionId:
          jsonn['session_id'] != null ? jsonn['session_id'].toString() : null,
      eventName:
          jsonn['event_name'] != null ? jsonn['event_name'].toString() : '',
      eventCategory: jsonn['event_category'] != null
          ? jsonn['event_category'].toString()
          : null,
      eventProperties: jsonn['event_properties'] != null
          ? jsonn['event_properties'] as Map<String, dynamic>
          : null,
      platform: jsonn['platform'] != null ? jsonn['platform'].toString() : null,
      appVersion:
          jsonn['app_version'] != null ? jsonn['app_version'].toString() : null,
      deviceInfo: jsonn['device_info'] != null
          ? jsonn['device_info'] as Map<String, dynamic>
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? sessionId,
    String? eventName,
    String? eventCategory,
    Map<String, dynamic>? eventProperties,
    String? platform,
    String? appVersion,
    Map<String, dynamic>? deviceInfo,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (sessionId != null) 'session_id': sessionId,
      if (eventName != null) 'event_name': eventName,
      if (eventCategory != null) 'event_category': eventCategory,
      if (eventProperties != null) 'event_properties': eventProperties,
      if (platform != null) 'platform': platform,
      if (appVersion != null) 'app_version': appVersion,
      if (deviceInfo != null) 'device_info': deviceInfo,
      if (createdAt != null) 'created_at': createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      sessionId: sessionId,
      eventName: eventName,
      eventCategory: eventCategory,
      eventProperties: eventProperties,
      platform: platform,
      appVersion: appVersion,
      deviceInfo: deviceInfo,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  AnalyticsEvents copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? sessionId = _unset,
    Object? eventName = _unset,
    Object? eventCategory = _unset,
    Object? eventProperties = _unset,
    Object? platform = _unset,
    Object? appVersion = _unset,
    Object? deviceInfo = _unset,
    Object? createdAt = _unset,
  }) {
    return AnalyticsEvents(
      id: id == _unset ? this.id : id as String,
      userId: userId == _unset ? this.userId : userId as String?,
      sessionId: sessionId == _unset ? this.sessionId : sessionId as String?,
      eventName: eventName == _unset ? this.eventName : eventName as String,
      eventCategory: eventCategory == _unset
          ? this.eventCategory
          : eventCategory as String?,
      eventProperties: eventProperties == _unset
          ? this.eventProperties
          : eventProperties as Map<String, dynamic>?,
      platform: platform == _unset ? this.platform : platform as String?,
      appVersion:
          appVersion == _unset ? this.appVersion : appVersion as String?,
      deviceInfo: deviceInfo == _unset
          ? this.deviceInfo
          : deviceInfo as Map<String, dynamic>?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
    );
  }
}
