// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class AppConfig implements SupadartClass<AppConfig> {
  final String key;
  final Map<String, dynamic> value;
  final String? description;
  final bool? isPublic;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const AppConfig({
    required this.key,
    required this.value,
    this.description,
    this.isPublic,
    this.createdAt,
    this.updatedAt,
  });

  static String get table_name => 'app_config';
  static String get c_key => 'key';
  static String get c_value => 'value';
  static String get c_description => 'description';
  static String get c_isPublic => 'is_public';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<AppConfig> converter(List<Map<String, dynamic>> data) {
    return data.map(AppConfig.fromJson).toList();
  }

  static AppConfig converterSingle(Map<String, dynamic> data) {
    return AppConfig.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? key,
    Map<String, dynamic>? value,
    String? description,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (key != null) 'key': key,
      if (value != null) 'value': value,
      if (description != null) 'description': description,
      if (isPublic != null) 'is_public': isPublic,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? key,
    required Map<String, dynamic> value,
    String? description,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      key: key,
      value: value,
      description: description,
      isPublic: isPublic,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? key,
    Map<String, dynamic>? value,
    String? description,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      key: key,
      value: value,
      description: description,
      isPublic: isPublic,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory AppConfig.fromJson(Map<String, dynamic> jsonn) {
    return AppConfig(
      key: jsonn['key'] != null ? jsonn['key'].toString() : '',
      value: jsonn['value'] != null
          ? jsonn['value'] as Map<String, dynamic>
          : <String, dynamic>{},
      description:
          jsonn['description'] != null ? jsonn['description'].toString() : null,
      isPublic: jsonn['is_public'] != null ? jsonn['is_public'] as bool : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
    );
  }

  static Object New({
    String? key,
    Map<String, dynamic>? value,
    String? description,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (key != null) 'key': key,
      if (value != null) 'value': value,
      if (description != null) 'description': description,
      if (isPublic != null) 'is_public': isPublic,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      key: key,
      value: value,
      description: description,
      isPublic: isPublic,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  AppConfig copyWith({
    Object? key = _unset,
    Object? value = _unset,
    Object? description = _unset,
    Object? isPublic = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return AppConfig(
      key: key == _unset ? this.key : key as String,
      value: value == _unset ? this.value : value as Map<String, dynamic>,
      description:
          description == _unset ? this.description : description as String?,
      isPublic: isPublic == _unset ? this.isPublic : isPublic as bool?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
    );
  }
}
