// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class CheckinHistoryView implements SupadartClass<CheckinHistoryView> {
  final String? id;
  final String? userId;
  final String? categoryId;
  final String? userCategoryId;
  final num? wellnessLevel;
  final String? summary;
  final String? insights;
  final String? status;
  final int? currentQuestion;
  final int? totalQuestions;
  final Map<String, dynamic>? responses;
  final num? completionPercentage;
  final DateTime? startedAt;
  final DateTime? completedAt;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final Map<String, dynamic>? metadata;
  final String? brief;
  final String? insight;
  final Map<String, dynamic>? mood;
  final int? questionsAsked;
  final String? categoryName;
  final String? categoryColor;
  final String? categoryIcon;

  const CheckinHistoryView({
    this.id,
    this.userId,
    this.categoryId,
    this.userCategoryId,
    this.wellnessLevel,
    this.summary,
    this.insights,
    this.status,
    this.currentQuestion,
    this.totalQuestions,
    this.responses,
    this.completionPercentage,
    this.startedAt,
    this.completedAt,
    this.createdAt,
    this.updatedAt,
    this.metadata,
    this.brief,
    this.insight,
    this.mood,
    this.questionsAsked,
    this.categoryName,
    this.categoryColor,
    this.categoryIcon,
  });

  static String get table_name => 'checkin_history_view';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_categoryId => 'category_id';
  static String get c_userCategoryId => 'user_category_id';
  static String get c_wellnessLevel => 'wellness_level';
  static String get c_summary => 'summary';
  static String get c_insights => 'insights';
  static String get c_status => 'status';
  static String get c_currentQuestion => 'current_question';
  static String get c_totalQuestions => 'total_questions';
  static String get c_responses => 'responses';
  static String get c_completionPercentage => 'completion_percentage';
  static String get c_startedAt => 'started_at';
  static String get c_completedAt => 'completed_at';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_metadata => 'metadata';
  static String get c_brief => 'brief';
  static String get c_insight => 'insight';
  static String get c_mood => 'mood';
  static String get c_questionsAsked => 'questions_asked';
  static String get c_categoryName => 'category_name';
  static String get c_categoryColor => 'category_color';
  static String get c_categoryIcon => 'category_icon';

  static List<CheckinHistoryView> converter(List<Map<String, dynamic>> data) {
    return data.map(CheckinHistoryView.fromJson).toList();
  }

  static CheckinHistoryView converterSingle(Map<String, dynamic> data) {
    return CheckinHistoryView.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? categoryId,
    String? userCategoryId,
    num? wellnessLevel,
    String? summary,
    String? insights,
    String? status,
    int? currentQuestion,
    int? totalQuestions,
    Map<String, dynamic>? responses,
    num? completionPercentage,
    DateTime? startedAt,
    DateTime? completedAt,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
    String? brief,
    String? insight,
    Map<String, dynamic>? mood,
    int? questionsAsked,
    String? categoryName,
    String? categoryColor,
    String? categoryIcon,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (userCategoryId != null) 'user_category_id': userCategoryId,
      if (wellnessLevel != null) 'wellness_level': wellnessLevel.toString(),
      if (summary != null) 'summary': summary,
      if (insights != null) 'insights': insights,
      if (status != null) 'status': status,
      if (currentQuestion != null) 'current_question': currentQuestion,
      if (totalQuestions != null) 'total_questions': totalQuestions,
      if (responses != null) 'responses': responses,
      if (completionPercentage != null)
        'completion_percentage': completionPercentage.toString(),
      if (startedAt != null) 'started_at': startedAt.toUtc().toIso8601String(),
      if (completedAt != null)
        'completed_at': completedAt.toUtc().toIso8601String(),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (metadata != null) 'metadata': metadata,
      if (brief != null) 'brief': brief,
      if (insight != null) 'insight': insight,
      if (mood != null) 'mood': mood,
      if (questionsAsked != null) 'questions_asked': questionsAsked,
      if (categoryName != null) 'category_name': categoryName,
      if (categoryColor != null) 'category_color': categoryColor,
      if (categoryIcon != null) 'category_icon': categoryIcon,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? userId,
    String? categoryId,
    String? userCategoryId,
    num? wellnessLevel,
    String? summary,
    String? insights,
    String? status,
    int? currentQuestion,
    int? totalQuestions,
    Map<String, dynamic>? responses,
    num? completionPercentage,
    DateTime? startedAt,
    DateTime? completedAt,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
    String? brief,
    String? insight,
    Map<String, dynamic>? mood,
    int? questionsAsked,
    String? categoryName,
    String? categoryColor,
    String? categoryIcon,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      userCategoryId: userCategoryId,
      wellnessLevel: wellnessLevel,
      summary: summary,
      insights: insights,
      status: status,
      currentQuestion: currentQuestion,
      totalQuestions: totalQuestions,
      responses: responses,
      completionPercentage: completionPercentage,
      startedAt: startedAt,
      completedAt: completedAt,
      createdAt: createdAt,
      updatedAt: updatedAt,
      metadata: metadata,
      brief: brief,
      insight: insight,
      mood: mood,
      questionsAsked: questionsAsked,
      categoryName: categoryName,
      categoryColor: categoryColor,
      categoryIcon: categoryIcon,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? categoryId,
    String? userCategoryId,
    num? wellnessLevel,
    String? summary,
    String? insights,
    String? status,
    int? currentQuestion,
    int? totalQuestions,
    Map<String, dynamic>? responses,
    num? completionPercentage,
    DateTime? startedAt,
    DateTime? completedAt,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
    String? brief,
    String? insight,
    Map<String, dynamic>? mood,
    int? questionsAsked,
    String? categoryName,
    String? categoryColor,
    String? categoryIcon,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      userCategoryId: userCategoryId,
      wellnessLevel: wellnessLevel,
      summary: summary,
      insights: insights,
      status: status,
      currentQuestion: currentQuestion,
      totalQuestions: totalQuestions,
      responses: responses,
      completionPercentage: completionPercentage,
      startedAt: startedAt,
      completedAt: completedAt,
      createdAt: createdAt,
      updatedAt: updatedAt,
      metadata: metadata,
      brief: brief,
      insight: insight,
      mood: mood,
      questionsAsked: questionsAsked,
      categoryName: categoryName,
      categoryColor: categoryColor,
      categoryIcon: categoryIcon,
    );
  }

  factory CheckinHistoryView.fromJson(Map<String, dynamic> jsonn) {
    return CheckinHistoryView(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      categoryId:
          jsonn['category_id'] != null ? jsonn['category_id'].toString() : null,
      userCategoryId: jsonn['user_category_id'] != null
          ? jsonn['user_category_id'].toString()
          : null,
      wellnessLevel: jsonn['wellness_level'] != null
          ? num.parse(jsonn['wellness_level'].toString())
          : null,
      summary: jsonn['summary'] != null ? jsonn['summary'].toString() : null,
      insights: jsonn['insights'] != null ? jsonn['insights'].toString() : null,
      status: jsonn['status'] != null ? jsonn['status'].toString() : null,
      currentQuestion: jsonn['current_question'] != null
          ? int.parse(jsonn['current_question'].toString())
          : null,
      totalQuestions: jsonn['total_questions'] != null
          ? int.parse(jsonn['total_questions'].toString())
          : null,
      responses: jsonn['responses'] != null
          ? jsonn['responses'] as Map<String, dynamic>
          : null,
      completionPercentage: jsonn['completion_percentage'] != null
          ? num.parse(jsonn['completion_percentage'].toString())
          : null,
      startedAt: jsonn['started_at'] != null
          ? DateTime.parse(jsonn['started_at'].toString())
          : null,
      completedAt: jsonn['completed_at'] != null
          ? DateTime.parse(jsonn['completed_at'].toString())
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
      brief: jsonn['brief'] != null ? jsonn['brief'].toString() : null,
      insight: jsonn['insight'] != null ? jsonn['insight'].toString() : null,
      mood:
          jsonn['mood'] != null ? jsonn['mood'] as Map<String, dynamic> : null,
      questionsAsked: jsonn['questions_asked'] != null
          ? int.parse(jsonn['questions_asked'].toString())
          : null,
      categoryName: jsonn['category_name'] != null
          ? jsonn['category_name'].toString()
          : null,
      categoryColor: jsonn['category_color'] != null
          ? jsonn['category_color'].toString()
          : null,
      categoryIcon: jsonn['category_icon'] != null
          ? jsonn['category_icon'].toString()
          : null,
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? categoryId,
    String? userCategoryId,
    num? wellnessLevel,
    String? summary,
    String? insights,
    String? status,
    int? currentQuestion,
    int? totalQuestions,
    Map<String, dynamic>? responses,
    num? completionPercentage,
    DateTime? startedAt,
    DateTime? completedAt,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? metadata,
    String? brief,
    String? insight,
    Map<String, dynamic>? mood,
    int? questionsAsked,
    String? categoryName,
    String? categoryColor,
    String? categoryIcon,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (userCategoryId != null) 'user_category_id': userCategoryId,
      if (wellnessLevel != null) 'wellness_level': wellnessLevel,
      if (summary != null) 'summary': summary,
      if (insights != null) 'insights': insights,
      if (status != null) 'status': status,
      if (currentQuestion != null) 'current_question': currentQuestion,
      if (totalQuestions != null) 'total_questions': totalQuestions,
      if (responses != null) 'responses': responses,
      if (completionPercentage != null)
        'completion_percentage': completionPercentage,
      if (startedAt != null) 'started_at': startedAt,
      if (completedAt != null) 'completed_at': completedAt,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (metadata != null) 'metadata': metadata,
      if (brief != null) 'brief': brief,
      if (insight != null) 'insight': insight,
      if (mood != null) 'mood': mood,
      if (questionsAsked != null) 'questions_asked': questionsAsked,
      if (categoryName != null) 'category_name': categoryName,
      if (categoryColor != null) 'category_color': categoryColor,
      if (categoryIcon != null) 'category_icon': categoryIcon,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      userCategoryId: userCategoryId,
      wellnessLevel: wellnessLevel,
      summary: summary,
      insights: insights,
      status: status,
      currentQuestion: currentQuestion,
      totalQuestions: totalQuestions,
      responses: responses,
      completionPercentage: completionPercentage,
      startedAt: startedAt,
      completedAt: completedAt,
      createdAt: createdAt,
      updatedAt: updatedAt,
      metadata: metadata,
      brief: brief,
      insight: insight,
      mood: mood,
      questionsAsked: questionsAsked,
      categoryName: categoryName,
      categoryColor: categoryColor,
      categoryIcon: categoryIcon,
    );
  }

  static const _unset = Object();
  CheckinHistoryView copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? categoryId = _unset,
    Object? userCategoryId = _unset,
    Object? wellnessLevel = _unset,
    Object? summary = _unset,
    Object? insights = _unset,
    Object? status = _unset,
    Object? currentQuestion = _unset,
    Object? totalQuestions = _unset,
    Object? responses = _unset,
    Object? completionPercentage = _unset,
    Object? startedAt = _unset,
    Object? completedAt = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? metadata = _unset,
    Object? brief = _unset,
    Object? insight = _unset,
    Object? mood = _unset,
    Object? questionsAsked = _unset,
    Object? categoryName = _unset,
    Object? categoryColor = _unset,
    Object? categoryIcon = _unset,
  }) {
    return CheckinHistoryView(
      id: id == _unset ? this.id : id as String?,
      userId: userId == _unset ? this.userId : userId as String?,
      categoryId:
          categoryId == _unset ? this.categoryId : categoryId as String?,
      userCategoryId: userCategoryId == _unset
          ? this.userCategoryId
          : userCategoryId as String?,
      wellnessLevel:
          wellnessLevel == _unset ? this.wellnessLevel : wellnessLevel as num?,
      summary: summary == _unset ? this.summary : summary as String?,
      insights: insights == _unset ? this.insights : insights as String?,
      status: status == _unset ? this.status : status as String?,
      currentQuestion: currentQuestion == _unset
          ? this.currentQuestion
          : currentQuestion as int?,
      totalQuestions: totalQuestions == _unset
          ? this.totalQuestions
          : totalQuestions as int?,
      responses: responses == _unset
          ? this.responses
          : responses as Map<String, dynamic>?,
      completionPercentage: completionPercentage == _unset
          ? this.completionPercentage
          : completionPercentage as num?,
      startedAt: startedAt == _unset ? this.startedAt : startedAt as DateTime?,
      completedAt:
          completedAt == _unset ? this.completedAt : completedAt as DateTime?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
      brief: brief == _unset ? this.brief : brief as String?,
      insight: insight == _unset ? this.insight : insight as String?,
      mood: mood == _unset ? this.mood : mood as Map<String, dynamic>?,
      questionsAsked: questionsAsked == _unset
          ? this.questionsAsked
          : questionsAsked as int?,
      categoryName:
          categoryName == _unset ? this.categoryName : categoryName as String?,
      categoryColor: categoryColor == _unset
          ? this.categoryColor
          : categoryColor as String?,
      categoryIcon:
          categoryIcon == _unset ? this.categoryIcon : categoryIcon as String?,
    );
  }
}
