// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class UserCheckins implements SupadartClass<UserCheckins> {
  final String? id;
  final String? userId;
  final String? categoryId;
  final DateTime? createdAt;
  final String? summary;
  final String? insight;
  final String? brief;
  final Map<String, dynamic>? mood;
  final String? categoryName;
  final int? checkinCount;

  const UserCheckins({
    this.id,
    this.userId,
    this.categoryId,
    this.createdAt,
    this.summary,
    this.insight,
    this.brief,
    this.mood,
    this.categoryName,
    this.checkinCount,
  });

  static String get table_name => 'user_checkins';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_categoryId => 'category_id';
  static String get c_createdAt => 'created_at';
  static String get c_summary => 'summary';
  static String get c_insight => 'insight';
  static String get c_brief => 'brief';
  static String get c_mood => 'mood';
  static String get c_categoryName => 'category_name';
  static String get c_checkinCount => 'checkin_count';

  static List<UserCheckins> converter(List<Map<String, dynamic>> data) {
    return data.map(UserCheckins.fromJson).toList();
  }

  static UserCheckins converterSingle(Map<String, dynamic> data) {
    return UserCheckins.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? categoryId,
    DateTime? createdAt,
    String? summary,
    String? insight,
    String? brief,
    Map<String, dynamic>? mood,
    String? categoryName,
    int? checkinCount,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (summary != null) 'summary': summary,
      if (insight != null) 'insight': insight,
      if (brief != null) 'brief': brief,
      if (mood != null) 'mood': mood,
      if (categoryName != null) 'category_name': categoryName,
      if (checkinCount != null) 'checkin_count': checkinCount,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? userId,
    String? categoryId,
    DateTime? createdAt,
    String? summary,
    String? insight,
    String? brief,
    Map<String, dynamic>? mood,
    String? categoryName,
    int? checkinCount,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      createdAt: createdAt,
      summary: summary,
      insight: insight,
      brief: brief,
      mood: mood,
      categoryName: categoryName,
      checkinCount: checkinCount,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? categoryId,
    DateTime? createdAt,
    String? summary,
    String? insight,
    String? brief,
    Map<String, dynamic>? mood,
    String? categoryName,
    int? checkinCount,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      createdAt: createdAt,
      summary: summary,
      insight: insight,
      brief: brief,
      mood: mood,
      categoryName: categoryName,
      checkinCount: checkinCount,
    );
  }

  factory UserCheckins.fromJson(Map<String, dynamic> jsonn) {
    return UserCheckins(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      categoryId:
          jsonn['category_id'] != null ? jsonn['category_id'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      summary: jsonn['summary'] != null ? jsonn['summary'].toString() : null,
      insight: jsonn['insight'] != null ? jsonn['insight'].toString() : null,
      brief: jsonn['brief'] != null ? jsonn['brief'].toString() : null,
      mood:
          jsonn['mood'] != null ? jsonn['mood'] as Map<String, dynamic> : null,
      categoryName: jsonn['category_name'] != null
          ? jsonn['category_name'].toString()
          : null,
      checkinCount: jsonn['checkin_count'] != null
          ? int.parse(jsonn['checkin_count'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? categoryId,
    DateTime? createdAt,
    String? summary,
    String? insight,
    String? brief,
    Map<String, dynamic>? mood,
    String? categoryName,
    int? checkinCount,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (createdAt != null) 'created_at': createdAt,
      if (summary != null) 'summary': summary,
      if (insight != null) 'insight': insight,
      if (brief != null) 'brief': brief,
      if (mood != null) 'mood': mood,
      if (categoryName != null) 'category_name': categoryName,
      if (checkinCount != null) 'checkin_count': checkinCount,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      createdAt: createdAt,
      summary: summary,
      insight: insight,
      brief: brief,
      mood: mood,
      categoryName: categoryName,
      checkinCount: checkinCount,
    );
  }

  static const _unset = Object();
  UserCheckins copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? categoryId = _unset,
    Object? createdAt = _unset,
    Object? summary = _unset,
    Object? insight = _unset,
    Object? brief = _unset,
    Object? mood = _unset,
    Object? categoryName = _unset,
    Object? checkinCount = _unset,
  }) {
    return UserCheckins(
      id: id == _unset ? this.id : id as String?,
      userId: userId == _unset ? this.userId : userId as String?,
      categoryId:
          categoryId == _unset ? this.categoryId : categoryId as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      summary: summary == _unset ? this.summary : summary as String?,
      insight: insight == _unset ? this.insight : insight as String?,
      brief: brief == _unset ? this.brief : brief as String?,
      mood: mood == _unset ? this.mood : mood as Map<String, dynamic>?,
      categoryName:
          categoryName == _unset ? this.categoryName : categoryName as String?,
      checkinCount:
          checkinCount == _unset ? this.checkinCount : checkinCount as int?,
    );
  }
}
