// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class ActiveRecommendations implements SupadartClass<ActiveRecommendations> {
  final String? id;
  final String? userId;
  final String? categoryId;
  final String? checkinMessageId;
  final String? parentRecommendationId;
  final String? title;
  final String? recommendationText;
  final String? action;
  final String? why;
  final String? recommendationType;
  final int? importance;
  final num? relevance;
  final List<String>? recommendedCategories;
  final String? context;
  final bool? isActive;
  final DateTime? viewedAt;
  final DateTime? dismissedAt;
  final DateTime? createdAt;
  final Map<String, dynamic>? metadata;
  final String? categoryName;
  final String? categoryIcon;
  final String? categoryColor;

  const ActiveRecommendations({
    this.id,
    this.userId,
    this.categoryId,
    this.checkinMessageId,
    this.parentRecommendationId,
    this.title,
    this.recommendationText,
    this.action,
    this.why,
    this.recommendationType,
    this.importance,
    this.relevance,
    this.recommendedCategories,
    this.context,
    this.isActive,
    this.viewedAt,
    this.dismissedAt,
    this.createdAt,
    this.metadata,
    this.categoryName,
    this.categoryIcon,
    this.categoryColor,
  });

  static String get table_name => 'active_recommendations';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_categoryId => 'category_id';
  static String get c_checkinMessageId => 'checkin_message_id';
  static String get c_parentRecommendationId => 'parent_recommendation_id';
  static String get c_title => 'title';
  static String get c_recommendationText => 'recommendation_text';
  static String get c_action => 'action';
  static String get c_why => 'why';
  static String get c_recommendationType => 'recommendation_type';
  static String get c_importance => 'importance';
  static String get c_relevance => 'relevance';
  static String get c_recommendedCategories => 'recommended_categories';
  static String get c_context => 'context';
  static String get c_isActive => 'is_active';
  static String get c_viewedAt => 'viewed_at';
  static String get c_dismissedAt => 'dismissed_at';
  static String get c_createdAt => 'created_at';
  static String get c_metadata => 'metadata';
  static String get c_categoryName => 'category_name';
  static String get c_categoryIcon => 'category_icon';
  static String get c_categoryColor => 'category_color';

  static List<ActiveRecommendations> converter(
      List<Map<String, dynamic>> data) {
    return data.map(ActiveRecommendations.fromJson).toList();
  }

  static ActiveRecommendations converterSingle(Map<String, dynamic> data) {
    return ActiveRecommendations.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? categoryId,
    String? checkinMessageId,
    String? parentRecommendationId,
    String? title,
    String? recommendationText,
    String? action,
    String? why,
    String? recommendationType,
    int? importance,
    num? relevance,
    List<String>? recommendedCategories,
    String? context,
    bool? isActive,
    DateTime? viewedAt,
    DateTime? dismissedAt,
    DateTime? createdAt,
    Map<String, dynamic>? metadata,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (checkinMessageId != null) 'checkin_message_id': checkinMessageId,
      if (parentRecommendationId != null)
        'parent_recommendation_id': parentRecommendationId,
      if (title != null) 'title': title,
      if (recommendationText != null) 'recommendation_text': recommendationText,
      if (action != null) 'action': action,
      if (why != null) 'why': why,
      if (recommendationType != null) 'recommendation_type': recommendationType,
      if (importance != null) 'importance': importance,
      if (relevance != null) 'relevance': relevance.toString(),
      if (recommendedCategories != null)
        'recommended_categories': recommendedCategories.map((e) => e).toList(),
      if (context != null) 'context': context,
      if (isActive != null) 'is_active': isActive,
      if (viewedAt != null) 'viewed_at': viewedAt.toUtc().toIso8601String(),
      if (dismissedAt != null)
        'dismissed_at': dismissedAt.toUtc().toIso8601String(),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (metadata != null) 'metadata': metadata,
      if (categoryName != null) 'category_name': categoryName,
      if (categoryIcon != null) 'category_icon': categoryIcon,
      if (categoryColor != null) 'category_color': categoryColor,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? userId,
    String? categoryId,
    String? checkinMessageId,
    String? parentRecommendationId,
    String? title,
    String? recommendationText,
    String? action,
    String? why,
    String? recommendationType,
    int? importance,
    num? relevance,
    List<String>? recommendedCategories,
    String? context,
    bool? isActive,
    DateTime? viewedAt,
    DateTime? dismissedAt,
    DateTime? createdAt,
    Map<String, dynamic>? metadata,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      checkinMessageId: checkinMessageId,
      parentRecommendationId: parentRecommendationId,
      title: title,
      recommendationText: recommendationText,
      action: action,
      why: why,
      recommendationType: recommendationType,
      importance: importance,
      relevance: relevance,
      recommendedCategories: recommendedCategories,
      context: context,
      isActive: isActive,
      viewedAt: viewedAt,
      dismissedAt: dismissedAt,
      createdAt: createdAt,
      metadata: metadata,
      categoryName: categoryName,
      categoryIcon: categoryIcon,
      categoryColor: categoryColor,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? categoryId,
    String? checkinMessageId,
    String? parentRecommendationId,
    String? title,
    String? recommendationText,
    String? action,
    String? why,
    String? recommendationType,
    int? importance,
    num? relevance,
    List<String>? recommendedCategories,
    String? context,
    bool? isActive,
    DateTime? viewedAt,
    DateTime? dismissedAt,
    DateTime? createdAt,
    Map<String, dynamic>? metadata,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      checkinMessageId: checkinMessageId,
      parentRecommendationId: parentRecommendationId,
      title: title,
      recommendationText: recommendationText,
      action: action,
      why: why,
      recommendationType: recommendationType,
      importance: importance,
      relevance: relevance,
      recommendedCategories: recommendedCategories,
      context: context,
      isActive: isActive,
      viewedAt: viewedAt,
      dismissedAt: dismissedAt,
      createdAt: createdAt,
      metadata: metadata,
      categoryName: categoryName,
      categoryIcon: categoryIcon,
      categoryColor: categoryColor,
    );
  }

  factory ActiveRecommendations.fromJson(Map<String, dynamic> jsonn) {
    return ActiveRecommendations(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      categoryId:
          jsonn['category_id'] != null ? jsonn['category_id'].toString() : null,
      checkinMessageId: jsonn['checkin_message_id'] != null
          ? jsonn['checkin_message_id'].toString()
          : null,
      parentRecommendationId: jsonn['parent_recommendation_id'] != null
          ? jsonn['parent_recommendation_id'].toString()
          : null,
      title: jsonn['title'] != null ? jsonn['title'].toString() : null,
      recommendationText: jsonn['recommendation_text'] != null
          ? jsonn['recommendation_text'].toString()
          : null,
      action: jsonn['action'] != null ? jsonn['action'].toString() : null,
      why: jsonn['why'] != null ? jsonn['why'].toString() : null,
      recommendationType: jsonn['recommendation_type'] != null
          ? jsonn['recommendation_type'].toString()
          : null,
      importance: jsonn['importance'] != null
          ? int.parse(jsonn['importance'].toString())
          : null,
      relevance: jsonn['relevance'] != null
          ? num.parse(jsonn['relevance'].toString())
          : null,
      recommendedCategories: jsonn['recommended_categories'] != null
          ? (jsonn['recommended_categories'] as List<dynamic>)
              .map((v) => v.toString())
              .toList()
          : null,
      context: jsonn['context'] != null ? jsonn['context'].toString() : null,
      isActive: jsonn['is_active'] != null ? jsonn['is_active'] as bool : null,
      viewedAt: jsonn['viewed_at'] != null
          ? DateTime.parse(jsonn['viewed_at'].toString())
          : null,
      dismissedAt: jsonn['dismissed_at'] != null
          ? DateTime.parse(jsonn['dismissed_at'].toString())
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
      categoryName: jsonn['category_name'] != null
          ? jsonn['category_name'].toString()
          : null,
      categoryIcon: jsonn['category_icon'] != null
          ? jsonn['category_icon'].toString()
          : null,
      categoryColor: jsonn['category_color'] != null
          ? jsonn['category_color'].toString()
          : null,
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? categoryId,
    String? checkinMessageId,
    String? parentRecommendationId,
    String? title,
    String? recommendationText,
    String? action,
    String? why,
    String? recommendationType,
    int? importance,
    num? relevance,
    List<String>? recommendedCategories,
    String? context,
    bool? isActive,
    DateTime? viewedAt,
    DateTime? dismissedAt,
    DateTime? createdAt,
    Map<String, dynamic>? metadata,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (categoryId != null) 'category_id': categoryId,
      if (checkinMessageId != null) 'checkin_message_id': checkinMessageId,
      if (parentRecommendationId != null)
        'parent_recommendation_id': parentRecommendationId,
      if (title != null) 'title': title,
      if (recommendationText != null) 'recommendation_text': recommendationText,
      if (action != null) 'action': action,
      if (why != null) 'why': why,
      if (recommendationType != null) 'recommendation_type': recommendationType,
      if (importance != null) 'importance': importance,
      if (relevance != null) 'relevance': relevance,
      if (recommendedCategories != null)
        'recommended_categories': recommendedCategories,
      if (context != null) 'context': context,
      if (isActive != null) 'is_active': isActive,
      if (viewedAt != null) 'viewed_at': viewedAt,
      if (dismissedAt != null) 'dismissed_at': dismissedAt,
      if (createdAt != null) 'created_at': createdAt,
      if (metadata != null) 'metadata': metadata,
      if (categoryName != null) 'category_name': categoryName,
      if (categoryIcon != null) 'category_icon': categoryIcon,
      if (categoryColor != null) 'category_color': categoryColor,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      categoryId: categoryId,
      checkinMessageId: checkinMessageId,
      parentRecommendationId: parentRecommendationId,
      title: title,
      recommendationText: recommendationText,
      action: action,
      why: why,
      recommendationType: recommendationType,
      importance: importance,
      relevance: relevance,
      recommendedCategories: recommendedCategories,
      context: context,
      isActive: isActive,
      viewedAt: viewedAt,
      dismissedAt: dismissedAt,
      createdAt: createdAt,
      metadata: metadata,
      categoryName: categoryName,
      categoryIcon: categoryIcon,
      categoryColor: categoryColor,
    );
  }

  static const _unset = Object();
  ActiveRecommendations copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? categoryId = _unset,
    Object? checkinMessageId = _unset,
    Object? parentRecommendationId = _unset,
    Object? title = _unset,
    Object? recommendationText = _unset,
    Object? action = _unset,
    Object? why = _unset,
    Object? recommendationType = _unset,
    Object? importance = _unset,
    Object? relevance = _unset,
    Object? recommendedCategories = _unset,
    Object? context = _unset,
    Object? isActive = _unset,
    Object? viewedAt = _unset,
    Object? dismissedAt = _unset,
    Object? createdAt = _unset,
    Object? metadata = _unset,
    Object? categoryName = _unset,
    Object? categoryIcon = _unset,
    Object? categoryColor = _unset,
  }) {
    return ActiveRecommendations(
      id: id == _unset ? this.id : id as String?,
      userId: userId == _unset ? this.userId : userId as String?,
      categoryId:
          categoryId == _unset ? this.categoryId : categoryId as String?,
      checkinMessageId: checkinMessageId == _unset
          ? this.checkinMessageId
          : checkinMessageId as String?,
      parentRecommendationId: parentRecommendationId == _unset
          ? this.parentRecommendationId
          : parentRecommendationId as String?,
      title: title == _unset ? this.title : title as String?,
      recommendationText: recommendationText == _unset
          ? this.recommendationText
          : recommendationText as String?,
      action: action == _unset ? this.action : action as String?,
      why: why == _unset ? this.why : why as String?,
      recommendationType: recommendationType == _unset
          ? this.recommendationType
          : recommendationType as String?,
      importance: importance == _unset ? this.importance : importance as int?,
      relevance: relevance == _unset ? this.relevance : relevance as num?,
      recommendedCategories: recommendedCategories == _unset
          ? this.recommendedCategories
          : recommendedCategories as List<String>?,
      context: context == _unset ? this.context : context as String?,
      isActive: isActive == _unset ? this.isActive : isActive as bool?,
      viewedAt: viewedAt == _unset ? this.viewedAt : viewedAt as DateTime?,
      dismissedAt:
          dismissedAt == _unset ? this.dismissedAt : dismissedAt as DateTime?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
      categoryName:
          categoryName == _unset ? this.categoryName : categoryName as String?,
      categoryIcon:
          categoryIcon == _unset ? this.categoryIcon : categoryIcon as String?,
      categoryColor: categoryColor == _unset
          ? this.categoryColor
          : categoryColor as String?,
    );
  }
}
