// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class UserProfilesWithCoaches
    implements SupadartClass<UserProfilesWithCoaches> {
  final String? id;
  final String? name;
  final String? coachId;
  final int? yearOfBirth;
  final String? sex;
  final Map<String, dynamic>? notificationSettings;
  final Map<String, dynamic>? moodConfig;
  final bool? voiceEnabled;
  final String? languageCode;
  final String? timezone;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final Map<String, dynamic>? coach;
  final String? avatarUrl;
  final Map<String, dynamic>? metadata;
  final String? coachName;
  final String? coachAvatar;
  final String? coachBio;
  final String? coachSex;
  final int? coachYearOfBirth;

  const UserProfilesWithCoaches({
    this.id,
    this.name,
    this.coachId,
    this.yearOfBirth,
    this.sex,
    this.notificationSettings,
    this.moodConfig,
    this.voiceEnabled,
    this.languageCode,
    this.timezone,
    this.createdAt,
    this.updatedAt,
    this.coach,
    this.avatarUrl,
    this.metadata,
    this.coachName,
    this.coachAvatar,
    this.coachBio,
    this.coachSex,
    this.coachYearOfBirth,
  });

  static String get table_name => 'user_profiles_with_coaches';
  static String get c_id => 'id';
  static String get c_name => 'name';
  static String get c_coachId => 'coach_id';
  static String get c_yearOfBirth => 'year_of_birth';
  static String get c_sex => 'sex';
  static String get c_notificationSettings => 'notification_settings';
  static String get c_moodConfig => 'mood_config';
  static String get c_voiceEnabled => 'voice_enabled';
  static String get c_languageCode => 'language_code';
  static String get c_timezone => 'timezone';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_coach => 'coach';
  static String get c_avatarUrl => 'avatar_url';
  static String get c_metadata => 'metadata';
  static String get c_coachName => 'coach_name';
  static String get c_coachAvatar => 'coach_avatar';
  static String get c_coachBio => 'coach_bio';
  static String get c_coachSex => 'coach_sex';
  static String get c_coachYearOfBirth => 'coach_year_of_birth';

  static List<UserProfilesWithCoaches> converter(
      List<Map<String, dynamic>> data) {
    return data.map(UserProfilesWithCoaches.fromJson).toList();
  }

  static UserProfilesWithCoaches converterSingle(Map<String, dynamic> data) {
    return UserProfilesWithCoaches.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? coachName,
    String? coachAvatar,
    String? coachBio,
    String? coachSex,
    int? coachYearOfBirth,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (coachId != null) 'coach_id': coachId,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (sex != null) 'sex': sex,
      if (notificationSettings != null)
        'notification_settings': notificationSettings,
      if (moodConfig != null) 'mood_config': moodConfig,
      if (voiceEnabled != null) 'voice_enabled': voiceEnabled,
      if (languageCode != null) 'language_code': languageCode,
      if (timezone != null) 'timezone': timezone,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (coach != null) 'coach': coach,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (metadata != null) 'metadata': metadata,
      if (coachName != null) 'coach_name': coachName,
      if (coachAvatar != null) 'coach_avatar': coachAvatar,
      if (coachBio != null) 'coach_bio': coachBio,
      if (coachSex != null) 'coach_sex': coachSex,
      if (coachYearOfBirth != null) 'coach_year_of_birth': coachYearOfBirth,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? coachName,
    String? coachAvatar,
    String? coachBio,
    String? coachSex,
    int? coachYearOfBirth,
  }) {
    return _generateMap(
      id: id,
      name: name,
      coachId: coachId,
      yearOfBirth: yearOfBirth,
      sex: sex,
      notificationSettings: notificationSettings,
      moodConfig: moodConfig,
      voiceEnabled: voiceEnabled,
      languageCode: languageCode,
      timezone: timezone,
      createdAt: createdAt,
      updatedAt: updatedAt,
      coach: coach,
      avatarUrl: avatarUrl,
      metadata: metadata,
      coachName: coachName,
      coachAvatar: coachAvatar,
      coachBio: coachBio,
      coachSex: coachSex,
      coachYearOfBirth: coachYearOfBirth,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? coachName,
    String? coachAvatar,
    String? coachBio,
    String? coachSex,
    int? coachYearOfBirth,
  }) {
    return _generateMap(
      id: id,
      name: name,
      coachId: coachId,
      yearOfBirth: yearOfBirth,
      sex: sex,
      notificationSettings: notificationSettings,
      moodConfig: moodConfig,
      voiceEnabled: voiceEnabled,
      languageCode: languageCode,
      timezone: timezone,
      createdAt: createdAt,
      updatedAt: updatedAt,
      coach: coach,
      avatarUrl: avatarUrl,
      metadata: metadata,
      coachName: coachName,
      coachAvatar: coachAvatar,
      coachBio: coachBio,
      coachSex: coachSex,
      coachYearOfBirth: coachYearOfBirth,
    );
  }

  factory UserProfilesWithCoaches.fromJson(Map<String, dynamic> jsonn) {
    return UserProfilesWithCoaches(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      coachId: jsonn['coach_id'] != null ? jsonn['coach_id'].toString() : null,
      yearOfBirth: jsonn['year_of_birth'] != null
          ? int.parse(jsonn['year_of_birth'].toString())
          : null,
      sex: jsonn['sex'] != null ? jsonn['sex'].toString() : null,
      notificationSettings: jsonn['notification_settings'] != null
          ? jsonn['notification_settings'] as Map<String, dynamic>
          : null,
      moodConfig: jsonn['mood_config'] != null
          ? jsonn['mood_config'] as Map<String, dynamic>
          : null,
      voiceEnabled: jsonn['voice_enabled'] != null
          ? jsonn['voice_enabled'] as bool
          : null,
      languageCode: jsonn['language_code'] != null
          ? jsonn['language_code'].toString()
          : null,
      timezone: jsonn['timezone'] != null ? jsonn['timezone'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      coach: jsonn['coach'] != null
          ? jsonn['coach'] as Map<String, dynamic>
          : null,
      avatarUrl:
          jsonn['avatar_url'] != null ? jsonn['avatar_url'].toString() : null,
      metadata: jsonn['metadata'] != null
          ? jsonn['metadata'] as Map<String, dynamic>
          : null,
      coachName:
          jsonn['coach_name'] != null ? jsonn['coach_name'].toString() : null,
      coachAvatar: jsonn['coach_avatar'] != null
          ? jsonn['coach_avatar'].toString()
          : null,
      coachBio:
          jsonn['coach_bio'] != null ? jsonn['coach_bio'].toString() : null,
      coachSex:
          jsonn['coach_sex'] != null ? jsonn['coach_sex'].toString() : null,
      coachYearOfBirth: jsonn['coach_year_of_birth'] != null
          ? int.parse(jsonn['coach_year_of_birth'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? name,
    String? coachId,
    int? yearOfBirth,
    String? sex,
    Map<String, dynamic>? notificationSettings,
    Map<String, dynamic>? moodConfig,
    bool? voiceEnabled,
    String? languageCode,
    String? timezone,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? coach,
    String? avatarUrl,
    Map<String, dynamic>? metadata,
    String? coachName,
    String? coachAvatar,
    String? coachBio,
    String? coachSex,
    int? coachYearOfBirth,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (coachId != null) 'coach_id': coachId,
      if (yearOfBirth != null) 'year_of_birth': yearOfBirth,
      if (sex != null) 'sex': sex,
      if (notificationSettings != null)
        'notification_settings': notificationSettings,
      if (moodConfig != null) 'mood_config': moodConfig,
      if (voiceEnabled != null) 'voice_enabled': voiceEnabled,
      if (languageCode != null) 'language_code': languageCode,
      if (timezone != null) 'timezone': timezone,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (coach != null) 'coach': coach,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (metadata != null) 'metadata': metadata,
      if (coachName != null) 'coach_name': coachName,
      if (coachAvatar != null) 'coach_avatar': coachAvatar,
      if (coachBio != null) 'coach_bio': coachBio,
      if (coachSex != null) 'coach_sex': coachSex,
      if (coachYearOfBirth != null) 'coach_year_of_birth': coachYearOfBirth,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      name: name,
      coachId: coachId,
      yearOfBirth: yearOfBirth,
      sex: sex,
      notificationSettings: notificationSettings,
      moodConfig: moodConfig,
      voiceEnabled: voiceEnabled,
      languageCode: languageCode,
      timezone: timezone,
      createdAt: createdAt,
      updatedAt: updatedAt,
      coach: coach,
      avatarUrl: avatarUrl,
      metadata: metadata,
      coachName: coachName,
      coachAvatar: coachAvatar,
      coachBio: coachBio,
      coachSex: coachSex,
      coachYearOfBirth: coachYearOfBirth,
    );
  }

  static const _unset = Object();
  UserProfilesWithCoaches copyWith({
    Object? id = _unset,
    Object? name = _unset,
    Object? coachId = _unset,
    Object? yearOfBirth = _unset,
    Object? sex = _unset,
    Object? notificationSettings = _unset,
    Object? moodConfig = _unset,
    Object? voiceEnabled = _unset,
    Object? languageCode = _unset,
    Object? timezone = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? coach = _unset,
    Object? avatarUrl = _unset,
    Object? metadata = _unset,
    Object? coachName = _unset,
    Object? coachAvatar = _unset,
    Object? coachBio = _unset,
    Object? coachSex = _unset,
    Object? coachYearOfBirth = _unset,
  }) {
    return UserProfilesWithCoaches(
      id: id == _unset ? this.id : id as String?,
      name: name == _unset ? this.name : name as String?,
      coachId: coachId == _unset ? this.coachId : coachId as String?,
      yearOfBirth:
          yearOfBirth == _unset ? this.yearOfBirth : yearOfBirth as int?,
      sex: sex == _unset ? this.sex : sex as String?,
      notificationSettings: notificationSettings == _unset
          ? this.notificationSettings
          : notificationSettings as Map<String, dynamic>?,
      moodConfig: moodConfig == _unset
          ? this.moodConfig
          : moodConfig as Map<String, dynamic>?,
      voiceEnabled:
          voiceEnabled == _unset ? this.voiceEnabled : voiceEnabled as bool?,
      languageCode:
          languageCode == _unset ? this.languageCode : languageCode as String?,
      timezone: timezone == _unset ? this.timezone : timezone as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      coach: coach == _unset ? this.coach : coach as Map<String, dynamic>?,
      avatarUrl: avatarUrl == _unset ? this.avatarUrl : avatarUrl as String?,
      metadata: metadata == _unset
          ? this.metadata
          : metadata as Map<String, dynamic>?,
      coachName: coachName == _unset ? this.coachName : coachName as String?,
      coachAvatar:
          coachAvatar == _unset ? this.coachAvatar : coachAvatar as String?,
      coachBio: coachBio == _unset ? this.coachBio : coachBio as String?,
      coachSex: coachSex == _unset ? this.coachSex : coachSex as String?,
      coachYearOfBirth: coachYearOfBirth == _unset
          ? this.coachYearOfBirth
          : coachYearOfBirth as int?,
    );
  }
}
