// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class MobileUserDashboard implements SupadartClass<MobileUserDashboard> {
  final String? userId;
  final String? firstName;
  final String? lastName;
  final String? profileImage;
  final String? coachId;
  final String? coachName;
  final String? coachImage;
  final BigInt? activeRecommendations;
  final BigInt? unreadMessages;
  final BigInt? completedCheckins;
  final DateTime? memberSince;

  const MobileUserDashboard({
    this.userId,
    this.firstName,
    this.lastName,
    this.profileImage,
    this.coachId,
    this.coachName,
    this.coachImage,
    this.activeRecommendations,
    this.unreadMessages,
    this.completedCheckins,
    this.memberSince,
  });

  static String get table_name => 'mobile_user_dashboard';
  static String get c_userId => 'user_id';
  static String get c_firstName => 'first_name';
  static String get c_lastName => 'last_name';
  static String get c_profileImage => 'profile_image';
  static String get c_coachId => 'coach_id';
  static String get c_coachName => 'coach_name';
  static String get c_coachImage => 'coach_image';
  static String get c_activeRecommendations => 'active_recommendations';
  static String get c_unreadMessages => 'unread_messages';
  static String get c_completedCheckins => 'completed_checkins';
  static String get c_memberSince => 'member_since';

  static List<MobileUserDashboard> converter(List<Map<String, dynamic>> data) {
    return data.map(MobileUserDashboard.fromJson).toList();
  }

  static MobileUserDashboard converterSingle(Map<String, dynamic> data) {
    return MobileUserDashboard.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? userId,
    String? firstName,
    String? lastName,
    String? profileImage,
    String? coachId,
    String? coachName,
    String? coachImage,
    BigInt? activeRecommendations,
    BigInt? unreadMessages,
    BigInt? completedCheckins,
    DateTime? memberSince,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (firstName != null) 'first_name': firstName,
      if (lastName != null) 'last_name': lastName,
      if (profileImage != null) 'profile_image': profileImage,
      if (coachId != null) 'coach_id': coachId,
      if (coachName != null) 'coach_name': coachName,
      if (coachImage != null) 'coach_image': coachImage,
      if (activeRecommendations != null)
        'active_recommendations': activeRecommendations.toString(),
      if (unreadMessages != null) 'unread_messages': unreadMessages.toString(),
      if (completedCheckins != null)
        'completed_checkins': completedCheckins.toString(),
      if (memberSince != null)
        'member_since': memberSince.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? userId,
    String? firstName,
    String? lastName,
    String? profileImage,
    String? coachId,
    String? coachName,
    String? coachImage,
    BigInt? activeRecommendations,
    BigInt? unreadMessages,
    BigInt? completedCheckins,
    DateTime? memberSince,
  }) {
    return _generateMap(
      userId: userId,
      firstName: firstName,
      lastName: lastName,
      profileImage: profileImage,
      coachId: coachId,
      coachName: coachName,
      coachImage: coachImage,
      activeRecommendations: activeRecommendations,
      unreadMessages: unreadMessages,
      completedCheckins: completedCheckins,
      memberSince: memberSince,
    );
  }

  static Map<String, dynamic> update({
    String? userId,
    String? firstName,
    String? lastName,
    String? profileImage,
    String? coachId,
    String? coachName,
    String? coachImage,
    BigInt? activeRecommendations,
    BigInt? unreadMessages,
    BigInt? completedCheckins,
    DateTime? memberSince,
  }) {
    return _generateMap(
      userId: userId,
      firstName: firstName,
      lastName: lastName,
      profileImage: profileImage,
      coachId: coachId,
      coachName: coachName,
      coachImage: coachImage,
      activeRecommendations: activeRecommendations,
      unreadMessages: unreadMessages,
      completedCheckins: completedCheckins,
      memberSince: memberSince,
    );
  }

  factory MobileUserDashboard.fromJson(Map<String, dynamic> jsonn) {
    return MobileUserDashboard(
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      firstName:
          jsonn['first_name'] != null ? jsonn['first_name'].toString() : null,
      lastName:
          jsonn['last_name'] != null ? jsonn['last_name'].toString() : null,
      profileImage: jsonn['profile_image'] != null
          ? jsonn['profile_image'].toString()
          : null,
      coachId: jsonn['coach_id'] != null ? jsonn['coach_id'].toString() : null,
      coachName:
          jsonn['coach_name'] != null ? jsonn['coach_name'].toString() : null,
      coachImage:
          jsonn['coach_image'] != null ? jsonn['coach_image'].toString() : null,
      activeRecommendations: jsonn['active_recommendations'] != null
          ? BigInt.parse(jsonn['active_recommendations'].toString())
          : null,
      unreadMessages: jsonn['unread_messages'] != null
          ? BigInt.parse(jsonn['unread_messages'].toString())
          : null,
      completedCheckins: jsonn['completed_checkins'] != null
          ? BigInt.parse(jsonn['completed_checkins'].toString())
          : null,
      memberSince: jsonn['member_since'] != null
          ? DateTime.parse(jsonn['member_since'].toString())
          : null,
    );
  }

  static Object New({
    String? userId,
    String? firstName,
    String? lastName,
    String? profileImage,
    String? coachId,
    String? coachName,
    String? coachImage,
    BigInt? activeRecommendations,
    BigInt? unreadMessages,
    BigInt? completedCheckins,
    DateTime? memberSince,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (firstName != null) 'first_name': firstName,
      if (lastName != null) 'last_name': lastName,
      if (profileImage != null) 'profile_image': profileImage,
      if (coachId != null) 'coach_id': coachId,
      if (coachName != null) 'coach_name': coachName,
      if (coachImage != null) 'coach_image': coachImage,
      if (activeRecommendations != null)
        'active_recommendations': activeRecommendations,
      if (unreadMessages != null) 'unread_messages': unreadMessages,
      if (completedCheckins != null) 'completed_checkins': completedCheckins,
      if (memberSince != null) 'member_since': memberSince,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      userId: userId,
      firstName: firstName,
      lastName: lastName,
      profileImage: profileImage,
      coachId: coachId,
      coachName: coachName,
      coachImage: coachImage,
      activeRecommendations: activeRecommendations,
      unreadMessages: unreadMessages,
      completedCheckins: completedCheckins,
      memberSince: memberSince,
    );
  }

  static const _unset = Object();
  MobileUserDashboard copyWith({
    Object? userId = _unset,
    Object? firstName = _unset,
    Object? lastName = _unset,
    Object? profileImage = _unset,
    Object? coachId = _unset,
    Object? coachName = _unset,
    Object? coachImage = _unset,
    Object? activeRecommendations = _unset,
    Object? unreadMessages = _unset,
    Object? completedCheckins = _unset,
    Object? memberSince = _unset,
  }) {
    return MobileUserDashboard(
      userId: userId == _unset ? this.userId : userId as String?,
      firstName: firstName == _unset ? this.firstName : firstName as String?,
      lastName: lastName == _unset ? this.lastName : lastName as String?,
      profileImage:
          profileImage == _unset ? this.profileImage : profileImage as String?,
      coachId: coachId == _unset ? this.coachId : coachId as String?,
      coachName: coachName == _unset ? this.coachName : coachName as String?,
      coachImage:
          coachImage == _unset ? this.coachImage : coachImage as String?,
      activeRecommendations: activeRecommendations == _unset
          ? this.activeRecommendations
          : activeRecommendations as BigInt?,
      unreadMessages: unreadMessages == _unset
          ? this.unreadMessages
          : unreadMessages as BigInt?,
      completedCheckins: completedCheckins == _unset
          ? this.completedCheckins
          : completedCheckins as BigInt?,
      memberSince:
          memberSince == _unset ? this.memberSince : memberSince as DateTime?,
    );
  }
}
