// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison,prefer_null_aware_operators

// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.

// SDK
import 'package:supabase_flutter/supabase_flutter.dart';

// No geobase needed
// No Intl package needed
export 'dart:convert';

// Supadart Class
abstract class SupadartClass<T> {
  static Map<String, dynamic> insert(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  static Map<String, dynamic> update(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  factory SupadartClass.fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }

  static converter(List<Map<String, dynamic>> data) {
    throw UnimplementedError();
  }

  static converterSingle(Map<String, dynamic> data) {
    throw UnimplementedError();
  }
}

// Supabase Client Extension
extension SupadartClient on SupabaseClient {
  SupabaseQueryBuilder get recommendations => from('recommendations');
  SupabaseQueryBuilder get audio_transcriptions => from('audio_transcriptions');
  SupabaseQueryBuilder get voice_transcriptions => from('voice_transcriptions');
  SupabaseQueryBuilder get offline_queue => from('offline_queue');
  SupabaseQueryBuilder get app_versions => from('app_versions');
  SupabaseQueryBuilder get user_profiles_normalized =>
      from('user_profiles_normalized');
  SupabaseQueryBuilder get mobile_user_dashboard =>
      from('mobile_user_dashboard');
  SupabaseQueryBuilder get check_ins => from('check_ins');
  SupabaseQueryBuilder get user_stats => from('user_stats');
  SupabaseQueryBuilder get recommendations_active =>
      from('recommendations_active');
  SupabaseQueryBuilder get user_checkins => from('user_checkins');
  SupabaseQueryBuilder get checkins => from('checkins');
  SupabaseQueryBuilder get user_profiles_with_coaches =>
      from('user_profiles_with_coaches');
  SupabaseQueryBuilder get recommendations_with_children =>
      from('recommendations_with_children');
  SupabaseQueryBuilder get messages_with_coach => from('messages_with_coach');
  SupabaseQueryBuilder get message_threads => from('message_threads');
  SupabaseQueryBuilder get profiles => from('profiles');
  SupabaseQueryBuilder get coaches => from('coaches');
  SupabaseQueryBuilder get profile_categories => from('profile_categories');
  SupabaseQueryBuilder get categories_with_user_preferences =>
      from('categories_with_user_preferences');
  SupabaseQueryBuilder get app_config => from('app_config');
  SupabaseQueryBuilder get admin_audio_analytics =>
      from('admin_audio_analytics');
  SupabaseQueryBuilder get checkin_answers => from('checkin_answers');
  SupabaseQueryBuilder get user_devices => from('user_devices');
  SupabaseQueryBuilder get user_categories => from('user_categories');
  SupabaseQueryBuilder get active_recommendations =>
      from('active_recommendations');
  SupabaseQueryBuilder get user_feedback => from('user_feedback');
  SupabaseQueryBuilder get analytics_events => from('analytics_events');
  SupabaseQueryBuilder get user_audio_analytics => from('user_audio_analytics');
  SupabaseQueryBuilder get audio_usage_logs => from('audio_usage_logs');
  SupabaseQueryBuilder get checkin_progress => from('checkin_progress');
  SupabaseQueryBuilder get test_cicd_verification =>
      from('test_cicd_verification');
  SupabaseQueryBuilder get system_logs => from('system_logs');
  SupabaseQueryBuilder get messages => from('messages');
  SupabaseQueryBuilder get profile_categories_detailed =>
      from('profile_categories_detailed');
  SupabaseQueryBuilder get checkin_history_view => from('checkin_history_view');
  SupabaseQueryBuilder get image_migrations => from('image_migrations');
  SupabaseQueryBuilder get checkins_with_answers =>
      from('checkins_with_answers');
  SupabaseQueryBuilder get user_app_versions => from('user_app_versions');
  SupabaseQueryBuilder get categories => from('categories');
  SupabaseQueryBuilder get checkin_templates => from('checkin_templates');
  SupabaseQueryBuilder get health_cards => from('health_cards');
  SupabaseQueryBuilder get mobile_recommendations_feed =>
      from('mobile_recommendations_feed');
  SupabaseQueryBuilder get checkin_analytics => from('checkin_analytics');
}

// Supabase Storage Client Extension
extension SupadartStorageClient on SupabaseStorageClient {}

// Enums
enum SEX { male, female, non_binary, other, prefer_not_to_say }

enum ROLE { user, assistant, system }

enum CONTENT_TYPE { text, voice, checkin, feedback }

enum STATUS { active, completed, abandoned }

enum RECOMMENDATION_TYPE { action, category, insight }

enum INTERACTION_TYPE { viewed, liked, dismissed, saved }

enum PLATFORM { ios, android, web }

enum TRANSCRIPTION_STATUS { pending, processing, completed, failed }

enum LOG_LEVEL { debug, info, warning, error }

// Utils
