#!/bin/bash

# Script to help set up GitHub secrets for automated deployment
# This script provides instructions and commands for setting up secrets

echo "==================================="
echo "GitHub Secrets Setup for Deployment"
echo "==================================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo ""
echo "1. SUPABASE_ACCESS_TOKEN"
echo "   - Get from: https://app.supabase.com/account/tokens"
echo "   - Click 'Generate new token'"
echo "   - Give it a name like 'GitHub Actions'"
echo ""
echo "2. SUPABASE_PROJECT_ID"
echo "   - Your project ID: ilnmgducvjnzmmznklws"
echo "   - Found in: Dashboard → Settings → General → Reference ID"
echo ""
echo "==================================="
echo "How to add secrets to GitHub:"
echo "==================================="
echo ""
echo "1. Go to your GitHub repository"
echo "2. Click 'Settings' tab"
echo "3. In the left sidebar, click 'Secrets and variables' → 'Actions'"
echo "4. Click 'New repository secret'"
echo "5. Add each secret with its name and value"
echo ""
echo "==================================="
echo "Using GitHub CLI (if installed):"
echo "==================================="
echo ""
echo "If you have GitHub CLI installed, you can run these commands:"
echo ""
echo "# Set your access token first:"
echo "export SUPABASE_ACCESS_TOKEN='your-token-here'"
echo ""
echo "# Then run these commands:"
echo "gh secret set SUPABASE_ACCESS_TOKEN --body \"\$SUPABASE_ACCESS_TOKEN\""
echo "gh secret set SUPABASE_PROJECT_ID --body \"ilnmgducvjnzmmznklws\""
echo ""
echo "==================================="
echo "Testing locally before GitHub:"
echo "==================================="
echo ""
echo "Test the deployment locally first:"
echo ""
echo "export SUPABASE_ACCESS_TOKEN='your-token-here'"
echo "export SUPABASE_PROJECT_ID='ilnmgducvjnzmmznklws'"
echo "./scripts/deploy-edge-functions.sh"
echo ""