#!/bin/bash

echo "Setting up Supabase database password..."
echo ""
echo "To fix the CLI authentication issue, you need to:"
echo ""
echo "1. Go to your Supabase Dashboard"
echo "2. Navigate to Settings > Database"
echo "3. Find your database password or reset it"
echo "4. Note: Use only letters for the password (no special characters)"
echo ""
echo "Then run one of these commands:"
echo ""
echo "Option 1 - Set environment variable:"
echo "export SUPABASE_DB_PASSWORD='your-actual-password'"
echo "./supabase-cli db push"
echo ""
echo "Option 2 - Pass password directly:"
echo "./supabase-cli db push -p 'your-actual-password'"
echo ""
echo "Option 3 - Use direct connection (not pooler):"
echo "Check if your connection string uses pooler (port 6543)"
echo "You might need to use the direct connection instead"