// Totalis Types v1.0.99
// Generated: 2025-06-01T08:45:00Z
// DO NOT EDIT - This file is automatically generated

// Test Types for validation
class TestUser {
  final String id;
  final String name;
  final String? email;

  TestUser({
    required this.id,
    required this.name,
    this.email,
  });

  factory TestUser.fromJson(Map<String, dynamic> json) => TestUser(
        id: json['id'],
        name: json['name'],
        email: json['email'],
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'email': email,
      };
}

// Utilities
class DateTimeUtils {
  static DateTime fromJson(String json) => DateTime.parse(json);
  static String toJson(DateTime object) => object.toIso8601String();
  
  static DateTime? fromJsonNullable(String? json) => 
    json != null ? DateTime.parse(json) : null;
  static String? toJsonNullable(DateTime? object) => object?.toIso8601String();
}

// Version info
const String totalisTypesVersion = '1.0.99';
const String generatedAt = '2025-06-01T08:45:00Z';