name: Deploy Edge Functions

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:
    inputs:
      function_name:
        description: 'Specific function to deploy (leave empty to deploy all)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy All Edge Functions
        if: github.event.inputs.function_name == ''
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          # Deploy all functions using the --use-api flag to avoid Docker
          for func in supabase/functions/*/; do
            if [ -d "$func" ]; then
              func_name=$(basename "$func")
              echo "Deploying function: $func_name"
              supabase functions deploy "$func_name" --use-api --project-ref $SUPABASE_PROJECT_ID
            fi
          done
      
      - name: Deploy Specific Edge Function
        if: github.event.inputs.function_name != ''
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          echo "Deploying function: ${{ github.event.inputs.function_name }}"
          supabase functions deploy ${{ github.event.inputs.function_name }} --use-api --project-ref $SUPABASE_PROJECT_ID
      
      - name: List deployed functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase functions list --project-ref $SUPABASE_PROJECT_ID