name: Pre-Preview Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'supabase/**'
      - 'src/**'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  static-validation:
    runs-on: ubuntu-latest
    name: Fast Static Validation
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Report Job Start
        if: always()
        uses: ./.github/actions/update-status
        with:
          job_name: 'Fast Static Validation'
          status: 'in_progress'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.0

      - name: Validate Migration Naming
        id: migration_check
        run: |
          echo "🔍 Checking migration naming convention..."
          
          errors='[]'
          has_error=false
          
          for file in supabase/migrations/*.sql; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              # Check format: YYYYMMDDHHMMSS_prefix_description.sql
              if ! [[ "$filename" =~ ^[0-9]{14}_(feat|fix|refactor|hf)_[a-z0-9_]+\.sql$ ]]; then
                echo "❌ Invalid migration name: $filename"
                echo "Expected format: YYYYMMDDHHMMSS_prefix_description.sql"
                echo "Valid prefixes: feat_, fix_, refactor_, hf_"
                
                # Build error JSON
                error_msg="Invalid migration name: $filename"
                suggestion="Rename to format: YYYYMMDDHHMMSS_prefix_description.sql"
                errors=$(echo "$errors" | jq --arg msg "$error_msg" --arg file "$file" --arg sug "$suggestion" \
                  '. + [{"type": "validation_error", "message": $msg, "file": $file, "suggestion": $sug}]')
                has_error=true
              fi
            fi
          done
          
          echo "errors=$errors" >> $GITHUB_OUTPUT
          
          if [ "$has_error" = true ]; then
            exit 1
          fi
          
          echo "✅ All migrations follow naming convention"

      - name: Quick SQL Syntax Check
        run: |
          echo "🔍 Checking SQL syntax..."
          
          for file in supabase/migrations/*.sql; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              
              # Check for common SQL errors
              if grep -E ";;" "$file"; then
                echo "❌ Double semicolon found in: $filename"
                exit 1
              fi
              
              if grep -E "^\s*--[^-]" "$file" | grep -v "^\s*--\s"; then
                echo "❌ Invalid comment format in: $filename (use -- with space)"
                exit 1
              fi
              
              # Check for required safety patterns
              if ! grep -qE "(IF NOT EXISTS|IF EXISTS|OR REPLACE)" "$file"; then
                echo "⚠️  Warning: Migration may not be idempotent: $filename"
              fi
            fi
          done
          echo "✅ SQL syntax validation passed"

      - name: TypeScript Type Check
        run: |
          echo "🔍 Type checking Edge Functions..."
          
          # Check each function individually to get proper error reporting
          failed_functions=""
          
          for function_dir in supabase/functions/*/; do
            if [ -d "$function_dir" ] && [ -f "$function_dir/index.ts" ]; then
              function_name=$(basename "$function_dir")
              
              # Skip _shared directory
              if [ "$function_name" = "_shared" ]; then
                continue
              fi
              
              echo "Checking $function_name..."
              
              # Run deno check and capture result
              if ! (cd "$function_dir" && deno check --no-lock index.ts 2>&1); then
                failed_functions="$failed_functions $function_name"
                echo "❌ Failed: $function_name"
              else
                echo "✅ Passed: $function_name"
              fi
            fi
          done
          
          if [ -n "$failed_functions" ]; then
            echo ""
            echo "❌ TypeScript validation failed for:$failed_functions"
            echo ""
            echo "Run locally to see detailed errors:"
            echo "cd supabase/functions/FUNCTION_NAME && deno check index.ts"
            exit 1
          fi
          
          echo "✅ All functions pass type checking"

      - name: Check for Hardcoded Secrets
        run: |
          echo "🔍 Scanning for hardcoded secrets..."
          
          # Patterns that indicate hardcoded secrets
          patterns=(
            "SUPABASE_SERVICE_ROLE_KEY\s*=\s*['\"][^'\"]+['\"]"
            "SUPABASE_ANON_KEY\s*=\s*['\"][^'\"]+['\"]"
            "OPENAI_API_KEY\s*=\s*['\"][^'\"]+['\"]"
            "sk-[a-zA-Z0-9]{48}"
            "eyJ[a-zA-Z0-9_-]{20,}"
          )
          
          found_secrets=false
          for pattern in "${patterns[@]}"; do
            if grep -rE "$pattern" supabase/functions --include="*.ts" --include="*.js"; then
              found_secrets=true
            fi
          done
          
          if [ "$found_secrets" = true ]; then
            echo "❌ Found hardcoded secrets! Use Deno.env.get() instead"
            exit 1
          fi
          
          echo "✅ No hardcoded secrets found"

      - name: Validate Required Files
        run: |
          echo "🔍 Checking required files..."
          
          # Check each function has required structure
          for function_dir in supabase/functions/*/; do
            if [ -d "$function_dir" ]; then
              function_name=$(basename "$function_dir")
              
              # Skip _shared directory
              if [ "$function_name" = "_shared" ]; then
                continue
              fi
              
              if [ ! -f "$function_dir/index.ts" ]; then
                echo "❌ Missing index.ts in: $function_name"
                exit 1
              fi
              
              # Type references are checked by deno check, no need to duplicate
            fi
          done
          
          echo "✅ All required files present"

      - name: Set Validation Result
        id: validation
        if: success()
        run: |
          echo "✅ All static validations passed!"
          echo "validation_passed=true" >> $GITHUB_OUTPUT
          
          # Try to create a comment on the PR (optional, don't fail if it can't)
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "✅ **Pre-preview validation passed!**
            
            All static checks completed successfully:
            - ✓ Migration naming convention
            - ✓ SQL syntax validation
            - ✓ TypeScript type checking
            - ✓ No hardcoded secrets
            - ✓ Required files present
            
            The Supabase preview environment will be created automatically." || echo "Note: Could not post PR comment (insufficient permissions)"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set Validation Failure
        if: failure()
        run: |
          echo "❌ Static validation failed"
          echo "validation_passed=false" >> $GITHUB_OUTPUT
          
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "❌ **Pre-preview validation failed!**
            
            Please fix the validation errors above.
            
            Once fixed, push your changes and validation will run again automatically." || echo "Note: Could not post PR comment (insufficient permissions)"
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Report Final Status
        if: always()
        uses: ./.github/actions/update-status
        with:
          job_name: 'Fast Static Validation'
          status: ${{ job.status }}
          duration: ${{ steps.migration_check.outcome && '5s' || '0s' }}
          errors: ${{ steps.migration_check.outputs.errors || '[]' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}