name: Preview Tests (60% Coverage)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  preview-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Supabase Preview to be ready
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-preview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Supabase Preview'
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 300
          intervalSeconds: 15

      - name: Get preview branch credentials
        uses: 0xbigboss/supabase-branch-gh-action@v1
        id: supabase-branch
        with:
          supabase-access-token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          supabase-project-id: ${{ secrets.SUPABASE_PROJECT_ID }}
          wait-for-migrations: false
          timeout: 120

      - name: Display preview info
        run: |
          echo "🎯 Preview Environment Details:"
          echo "   API URL: ${{ steps.supabase-branch.outputs.api_url }}"
          echo "   Branch: ${{ github.head_ref }}"
          echo ""
          echo "🌱 Seed-First Architecture:"
          echo "   - Test users with deterministic IDs"
          echo "   - 60% test coverage target"
          echo "   - Auth-dependent tests deferred to production"

      - name: Setup Supabase CLI
        run: |
          cd /tmp
          wget -qO- https://github.com/supabase/cli/releases/download/v2.23.8/supabase_linux_amd64.tar.gz | tar xvz
          sudo mv supabase /usr/local/bin/
          cd $GITHUB_WORKSPACE
          supabase --version

      - name: Force seed execution before migrations
        run: |
          # Extract project ref from preview URL
          PREVIEW_API_URL="${{ steps.supabase-branch.outputs.api_url }}"
          PREVIEW_PROJECT_REF=$(echo $PREVIEW_API_URL | grep -oP '(?<=https://)[^.]+')
          echo "Preview project ref: $PREVIEW_PROJECT_REF"
          
          # Login and link to preview project
          supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          supabase link --project-ref $PREVIEW_PROJECT_REF
          
          # Force seed execution
          echo "🌱 Running seed.sql to create test users..."
          supabase db seed --debug || true
          
          # Verify seed ran
          echo "✅ Seed execution completed"

      - name: Verify test data exists
        env:
          DATABASE_URL: postgresql://postgres:${{ steps.supabase-branch.outputs.db_password }}@${{ steps.supabase-branch.outputs.db_host }}:${{ steps.supabase-branch.outputs.db_port }}/postgres
        run: |
          echo "🔍 Checking for test users in auth.users..."
          
          # Use Node.js to check since we can't connect directly to IPv6 from GitHub Actions
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(
            '${{ steps.supabase-branch.outputs.api_url }}'.replace('/rest/v1', ''),
            '${{ steps.supabase-branch.outputs.service_role_key }}'
          );
          
          (async () => {
            // Check if test users exist
            const { data: testUser } = await supabase.auth.admin.getUserById('11111111-1111-1111-1111-111111111111');
            
            if (testUser?.user) {
              console.log('✅ Test user 1 found:', testUser.user.email);
            } else {
              console.log('⚠️  Test user 1 not found - tests may fail');
            }
            
            // Check categories
            const { data: categories, error } = await supabase
              .from('categories')
              .select('count')
              .single();
              
            console.log('📊 Categories count:', categories?.count || 0);
          })();
          " || echo "⚠️  Could not verify test data"

      - name: Run Preview-Safe Tests (60% Coverage)
        env:
          SUPABASE_URL: ${{ steps.supabase-branch.outputs.api_url }}
          SUPABASE_ANON_KEY: ${{ steps.supabase-branch.outputs.anon_key }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ steps.supabase-branch.outputs.service_role_key }}
          DATABASE_URL: postgresql://postgres:${{ steps.supabase-branch.outputs.db_password }}@${{ steps.supabase-branch.outputs.db_host }}:${{ steps.supabase-branch.outputs.db_port }}/postgres
          ENVIRONMENT: preview
          NODE_ENV: test
          IS_PREVIEW: true
          TEST_CATEGORY: preview-safe
        run: |
          echo "🧪 Running preview-safe tests..."
          
          # Run only preview-safe tests
          npm test -- \
            --testNamePattern="preview.?safe|Preview Safe" \
            --coverage \
            --coverageThreshold='{"global":{"statements":60,"branches":50,"functions":55,"lines":60}}'

      - name: Generate coverage report
        if: always()
        run: |
          echo "### 📊 Preview Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Target**: 60% coverage for preview-safe tests" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f coverage/coverage-summary.json ]; then
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat coverage/coverage-summary.json | jq '.total' >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ No coverage report generated" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note**: Auth-dependent tests (40%) will run after merge to main" >> $GITHUB_STEP_SUMMARY

      - name: Comment test results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let coverage = { statements: 0, branches: 0, functions: 0, lines: 0 };
            
            try {
              const summary = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
              coverage = summary.total;
            } catch (e) {
              console.log('Could not read coverage summary');
            }
            
            const status = '${{ job.status }}' === 'success' ? '✅' : '❌';
            const previewUrl = '${{ steps.supabase-branch.outputs.api_url }}';
            
            let message = `## ${status} Preview Test Results\n\n`;
            
            message += `🎯 **Preview Environment**: \`${previewUrl}\`\n`;
            message += `🌱 **Test Architecture**: Seed-first with deterministic test users\n\n`;
            
            message += `### Coverage Report (Target: 60%)\n\n`;
            message += `| Metric | Coverage | Target | Status |\n`;
            message += `|--------|----------|--------|--------|\n`;
            message += `| Statements | ${coverage.statements.pct.toFixed(1)}% | 60% | ${coverage.statements.pct >= 60 ? '✅' : '⚠️'} |\n`;
            message += `| Branches | ${coverage.branches.pct.toFixed(1)}% | 50% | ${coverage.branches.pct >= 50 ? '✅' : '⚠️'} |\n`;
            message += `| Functions | ${coverage.functions.pct.toFixed(1)}% | 55% | ${coverage.functions.pct >= 55 ? '✅' : '⚠️'} |\n`;
            message += `| Lines | ${coverage.lines.pct.toFixed(1)}% | 60% | ${coverage.lines.pct >= 60 ? '✅' : '⚠️'} |\n\n`;
            
            if ('${{ job.status }}' === 'success') {
              message += `✅ **All preview-safe tests passed!**\n\n`;
              message += `The remaining 40% of tests (OAuth flows, password reset, etc.) will run after merge to main.`;
            } else {
              message += `❌ **Some tests failed**\n\n`;
              message += `Check the workflow logs for details. Common issues:\n`;
              message += `- Test users not created in seed.sql\n`;
              message += `- Migration order dependencies\n`;
              message += `- Preview branch limitations`;
            }
            
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } catch (error) {
              console.log('Could not post comment:', error.message);
            }