name: Publish Types on Release

on:
  release:
    types: [published]

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # Required for OIDC authentication to pub.dev
      
    steps:
      - name: Checkout repository at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Extract Version from Tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION from tag: $TAG_NAME"
          
      - name: Create Package Structure
        run: |
          # Download the latest types from the repository
          mkdir -p totalis_types/lib
          
          # Get the latest totalis_types content from the most recent workflow run
          # For now, we'll use a placeholder approach
          echo "// Totalis Types v${{ steps.version.outputs.version }}" > totalis_types/lib/totalis_types.dart
          echo "// This package was published from release ${{ github.ref }}" >> totalis_types/lib/totalis_types.dart
          echo "" >> totalis_types/lib/totalis_types.dart
          echo "// Note: This is a placeholder. The actual types are generated by the main workflow." >> totalis_types/lib/totalis_types.dart
          
      - name: Create pubspec.yaml
        run: |
          cat > totalis_types/pubspec.yaml << EOF
          name: totalis_types
          description: Type definitions for Totalis app - automatically generated from Supabase schema
          version: ${{ steps.version.outputs.version }}
          homepage: https://github.com/zitrono/totalis-supabase
          repository: https://github.com/zitrono/totalis-supabase
          
          environment:
            sdk: '>=3.0.0 <4.0.0'
          
          dependencies:
            json_annotation: ^4.8.1
          
          dev_dependencies:
            build_runner: ^2.4.7
            json_serializable: ^6.7.1
          EOF
          
      - name: Create README and LICENSE
        run: |
          echo "# Totalis Types" > totalis_types/README.md
          echo "" >> totalis_types/README.md
          echo "Automatically generated type definitions for the Totalis application." >> totalis_types/README.md
          echo "" >> totalis_types/README.md
          echo "Version: ${{ steps.version.outputs.version }}" >> totalis_types/README.md
          
          echo "MIT License" > totalis_types/LICENSE
          echo "" >> totalis_types/LICENSE
          echo "Copyright (c) $(date +%Y) Totalis" >> totalis_types/LICENSE
          
      - name: Publish to pub.dev
        run: |
          cd totalis_types
          dart pub publish --force